
// Tipos e interfaces completas
export type EstadoProducto = 'publicado' | 'borrador' | 'agotado' | 'programado';
export type CategoriaProducto = 'Ropa' | 'Accesorios' | 'Equipo' | 'Digital';

export interface VarianteProducto {
  id: string;
  talla?: string;
  color?: string;
  material?: string;
  sku: string;
  precio?: number;
  stock: number;
  imagen?: string;
}

export interface Producto {
  id: string;
  nombre: string;
  descripcionCorta: string;
  descripcionLarga: string;
  categoria: CategoriaProducto;
  subcategoria?: string;
  tags: string[];
  sku: string;
  codigoBarras?: string;

  // Imágenes
  imagenes: string[];
  imagenPrincipal: number;

  // Precios e Inventario
  precioRegular: number;
  precioOferta?: number;
  porcentajeDescuento?: number;
  costoProducto?: number;
  margenGanancia?: number;
  stock: number;
  alertaStockMinimo: number;
  permitirBackorder: boolean;

  // Estado y visibilidad
  estado: EstadoProducto;

  // Variantes
  tieneVariantes: boolean;
  variantes: VarianteProducto[];

  // Envío
  requiereEnvio: boolean;
  peso?: number;
  dimensiones?: {
    largo: number;
    ancho: number;
    alto: number;
  };
  tarifaEnvio?: 'gratis' | 'fija' | 'calculada';

  // SEO
  metaTitulo?: string;
  metaDescripcion?: string;
  urlSlug: string;

  // Métricas
  vistas: number;
  ventas: number;
  addToCart: number;
  tasaConversion: number;
  revenueGenerado: number;

  // Relaciones
  productosRelacionados: string[];

  // Fechas
  fechaCreacion: string;
  fechaActualizacion: string;
}

// Datos mockeados - 50 productos variados
const PRODUCTOS_MOCK: Producto[] = [
  // ROPA - Camisetas
  {
    id: '1',
    nombre: 'Camiseta Técnica Pro',
    descripcionCorta: 'Camiseta de alto rendimiento con tejido transpirable',
    descripcionLarga: 'Camiseta técnica diseñada para entrenamientos intensos. Fabricada con tejido de última generación que absorbe el sudor y mantiene tu cuerpo seco durante todo el ejercicio.',
    categoria: 'Ropa',
    subcategoria: 'Camisetas',
    tags: ['deportiva', 'transpirable', 'gym'],
    sku: 'CAM-TEC-001',
    imagenes: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500', 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=500'],
    imagenPrincipal: 0,
    precioRegular: 29.99,
    precioOferta: 24.99,
    porcentajeDescuento: 17,
    costoProducto: 12.00,
    margenGanancia: 108,
    stock: 150,
    alertaStockMinimo: 20,
    permitirBackorder: false,
    estado: 'publicado',
    tieneVariantes: true,
    variantes: [
      { id: 'v1', talla: 'S', color: 'Negro', sku: 'CAM-TEC-001-S-NEG', stock: 30 },
      { id: 'v2', talla: 'M', color: 'Negro', sku: 'CAM-TEC-001-M-NEG', stock: 50 },
      { id: 'v3', talla: 'L', color: 'Negro', sku: 'CAM-TEC-001-L-NEG', stock: 40 },
      { id: 'v4', talla: 'XL', color: 'Negro', sku: 'CAM-TEC-001-XL-NEG', stock: 30 },
    ],
    requiereEnvio: true,
    peso: 0.2,
    dimensiones: { largo: 30, ancho: 25, alto: 2 },
    tarifaEnvio: 'calculada',
    urlSlug: 'camiseta-tecnica-pro',
    vistas: 1234,
    ventas: 89,
    addToCart: 145,
    tasaConversion: 61.4,
    revenueGenerado: 2223.11,
    productosRelacionados: ['2', '3'],
    fechaCreacion: '2024-01-15',
    fechaActualizacion: '2024-12-01',
  },
  {
    id: '2',
    nombre: 'Camiseta Básica Fitness',
    descripcionCorta: 'Camiseta básica de algodón para uso diario',
    descripcionLarga: 'Camiseta de algodón 100% perfecta para tus entrenamientos ligeros o uso casual. Disponible en múltiples colores.',
    categoria: 'Ropa',
    subcategoria: 'Camisetas',
    tags: ['básica', 'algodón', 'casual'],
    sku: 'CAM-BAS-002',
    imagenes: ['https://images.unsplash.com/photo-1562157873-818bc0726f68?w=500'],
    imagenPrincipal: 0,
    precioRegular: 19.99,
    stock: 200,
    alertaStockMinimo: 30,
    permitirBackorder: true,
    estado: 'publicado',
    tieneVariantes: true,
    variantes: [
      { id: 'v5', talla: 'S', color: 'Blanco', sku: 'CAM-BAS-002-S-BLA', stock: 50 },
      { id: 'v6', talla: 'M', color: 'Blanco', sku: 'CAM-BAS-002-M-BLA', stock: 60 },
      { id: 'v7', talla: 'L', color: 'Azul', sku: 'CAM-BAS-002-L-AZU', stock: 50 },
      { id: 'v8', talla: 'XL', color: 'Azul', sku: 'CAM-BAS-002-XL-AZU', stock: 40 },
    ],
    requiereEnvio: true,
    peso: 0.25,
    tarifaEnvio: 'calculada',
    urlSlug: 'camiseta-basica-fitness',
    vistas: 890,
    ventas: 112,
    addToCart: 178,
    tasaConversion: 62.9,
    revenueGenerado: 2238.88,
    productosRelacionados: ['1', '4'],
    fechaCreacion: '2024-01-20',
    fechaActualizacion: '2024-11-28',
  },
  // ROPA - Sudaderas
  {
    id: '3',
    nombre: 'Sudadera Con Capucha Elite',
    descripcionCorta: 'Sudadera premium con capucha y bolsillo frontal',
    descripcionLarga: 'Sudadera de alta calidad perfecta para antes y después del entrenamiento. Tejido suave y cálido que te mantiene cómodo en cualquier situación.',
    categoria: 'Ropa',
    subcategoria: 'Sudaderas',
    tags: ['sudadera', 'capucha', 'premium'],
    sku: 'SUD-ELI-003',
    imagenes: ['https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=500', 'https://images.unsplash.com/photo-1620799140188-3b2a7428e26c?w=500'],
    imagenPrincipal: 0,
    precioRegular: 59.99,
    precioOferta: 49.99,
    porcentajeDescuento: 17,
    costoProducto: 25.00,
    stock: 80,
    alertaStockMinimo: 15,
    permitirBackorder: false,
    estado: 'publicado',
    tieneVariantes: true,
    variantes: [
      { id: 'v9', talla: 'M', color: 'Gris', sku: 'SUD-ELI-003-M-GRI', stock: 25 },
      { id: 'v10', talla: 'L', color: 'Gris', sku: 'SUD-ELI-003-L-GRI', stock: 30 },
      { id: 'v11', talla: 'XL', color: 'Negro', sku: 'SUD-ELI-003-XL-NEG', stock: 25 },
    ],
    requiereEnvio: true,
    peso: 0.6,
    dimensiones: { largo: 35, ancho: 30, alto: 5 },
    tarifaEnvio: 'calculada',
    urlSlug: 'sudadera-capucha-elite',
    vistas: 756,
    ventas: 45,
    addToCart: 89,
    tasaConversion: 50.6,
    revenueGenerado: 2249.55,
    productosRelacionados: ['1', '2'],
    fechaCreacion: '2024-02-01',
    fechaActualizacion: '2024-12-02',
  },
  {
    id: '4',
    nombre: 'Sudadera Crop Mujer',
    descripcionCorta: 'Sudadera corta de estilo moderno para mujer',
    descripcionLarga: 'Sudadera crop perfecta para combinar con tus leggings favoritos. Diseño moderno y cómodo.',
    categoria: 'Ropa',
    subcategoria: 'Sudaderas',
    tags: ['mujer', 'crop', 'moderno'],
    sku: 'SUD-CRO-004',
    imagenes: ['https://images.unsplash.com/photo-1614252368330-9e4bcff13b5b?w=500'],
    imagenPrincipal: 0,
    precioRegular: 44.99,
    stock: 4,
    alertaStockMinimo: 10,
    permitirBackorder: true,
    estado: 'publicado',
    tieneVariantes: true,
    variantes: [
      { id: 'v12', talla: 'XS', color: 'Rosa', sku: 'SUD-CRO-004-XS-ROS', stock: 1 },
      { id: 'v13', talla: 'S', color: 'Rosa', sku: 'SUD-CRO-004-S-ROS', stock: 2 },
      { id: 'v14', talla: 'M', color: 'Lila', sku: 'SUD-CRO-004-M-LIL', stock: 1 },
    ],
    requiereEnvio: true,
    peso: 0.4,
    tarifaEnvio: 'calculada',
    urlSlug: 'sudadera-crop-mujer',
    vistas: 445,
    ventas: 67,
    addToCart: 98,
    tasaConversion: 68.4,
    revenueGenerado: 3014.33,
    productosRelacionados: ['10', '11'],
    fechaCreacion: '2024-02-10',
    fechaActualizacion: '2024-12-01',
  },
  // ROPA - Gorras
  {
    id: '5',
    nombre: 'Gorra Deportiva Ajustable',
    descripcionCorta: 'Gorra con cierre ajustable y diseño deportivo',
    descripcionLarga: 'Gorra ligera perfecta para protegerte del sol durante tus entrenamientos al aire libre. Ajuste universal.',
    categoria: 'Ropa',
    subcategoria: 'Gorras',
    tags: ['gorra', 'deportiva', 'ajustable'],
    sku: 'GOR-DEP-005',
    imagenes: ['https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=500'],
    imagenPrincipal: 0,
    precioRegular: 24.99,
    stock: 120,
    alertaStockMinimo: 20,
    permitirBackorder: false,
    estado: 'publicado',
    tieneVariantes: false,
    variantes: [],
    requiereEnvio: true,
    peso: 0.1,
    tarifaEnvio: 'fija',
    urlSlug: 'gorra-deportiva-ajustable',
    vistas: 567,
    ventas: 78,
    addToCart: 112,
    tasaConversion: 69.6,
    revenueGenerado: 1949.22,
    productosRelacionados: ['1', '6'],
    fechaCreacion: '2024-03-01',
    fechaActualizacion: '2024-11-25',
  },
  // ACCESORIOS - Botellas
  {
    id: '6',
    nombre: 'Botella Térmica 750ml',
    descripcionCorta: 'Botella de acero inoxidable con aislamiento térmico',
    descripcionLarga: 'Mantén tus bebidas frías hasta 24h o calientes hasta 12h. Perfecta para el gym o la oficina.',
    categoria: 'Accesorios',
    subcategoria: 'Botellas',
    tags: ['botella', 'térmica', 'acero'],
    sku: 'BOT-TER-006',
    imagenes: ['https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=500'],
    imagenPrincipal: 0,
    precioRegular: 34.99,
    precioOferta: 29.99,
    porcentajeDescuento: 14,
    stock: 95,
    alertaStockMinimo: 15,
    permitirBackorder: false,
    estado: 'publicado',
    tieneVariantes: true,
    variantes: [
      { id: 'v15', color: 'Negro', sku: 'BOT-TER-006-NEG', stock: 35 },
      { id: 'v16', color: 'Azul', sku: 'BOT-TER-006-AZU', stock: 30 },
      { id: 'v17', color: 'Rosa', sku: 'BOT-TER-006-ROS', stock: 30 },
    ],
    requiereEnvio: true,
    peso: 0.35,
    tarifaEnvio: 'calculada',
    urlSlug: 'botella-termica-750ml',
    vistas: 923,
    ventas: 134,
    addToCart: 189,
    tasaConversion: 70.9,
    revenueGenerado: 4018.66,
    productosRelacionados: ['7', '8'],
    fechaCreacion: '2024-01-25',
    fechaActualizacion: '2024-12-03',
  },
  {
    id: '7',
    nombre: 'Botella Shaker Proteína',
    descripcionCorta: 'Shaker con compartimento para suplementos',
    descripcionLarga: 'Shaker profesional con sistema anti-grumos y compartimento extraíble para guardar tu proteína.',
    categoria: 'Accesorios',
    subcategoria: 'Botellas',
    tags: ['shaker', 'proteína', 'suplementos'],
    sku: 'BOT-SHA-007',
    imagenes: ['https://images.unsplash.com/photo-1584464491033-06628f3a6b7b?w=500'],
    imagenPrincipal: 0,
    precioRegular: 14.99,
    stock: 180,
    alertaStockMinimo: 25,
    permitirBackorder: true,
    estado: 'publicado',
    tieneVariantes: false,
    variantes: [],
    requiereEnvio: true,
    peso: 0.15,
    tarifaEnvio: 'fija',
    urlSlug: 'botella-shaker-proteina',
    vistas: 1123,
    ventas: 201,
    addToCart: 267,
    tasaConversion: 75.3,
    revenueGenerado: 3012.99,
    productosRelacionados: ['6', '30'],
    fechaCreacion: '2024-02-15',
    fechaActualizacion: '2024-11-30',
  },
  // ACCESORIOS - Toallas
  {
    id: '8',
    nombre: 'Toalla Deportiva Microfibra',
    descripcionCorta: 'Toalla de secado rápido con funda de transporte',
    descripcionLarga: 'Toalla de microfibra ultra absorbente y de secado rápido. Incluye funda de transporte compacta.',
    categoria: 'Accesorios',
    subcategoria: 'Toallas',
    tags: ['toalla', 'microfibra', 'gym'],
    sku: 'TOA-MIC-008',
    imagenes: ['https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=500'],
    imagenPrincipal: 0,
    precioRegular: 19.99,
    stock: 145,
    alertaStockMinimo: 20,
    permitirBackorder: false,
    estado: 'publicado',
    tieneVariantes: true,
    variantes: [
      { id: 'v18', color: 'Azul', sku: 'TOA-MIC-008-AZU', stock: 50 },
      { id: 'v19', color: 'Verde', sku: 'TOA-MIC-008-VER', stock: 50 },
      { id: 'v20', color: 'Gris', sku: 'TOA-MIC-008-GRI', stock: 45 },
    ],
    requiereEnvio: true,
    peso: 0.2,
    tarifaEnvio: 'calculada',
    urlSlug: 'toalla-deportiva-microfibra',
    vistas: 678,
    ventas: 89,
    addToCart: 134,
    tasaConversion: 66.4,
    revenueGenerado: 1779.11,
    productosRelacionados: ['6', '9'],
    fechaCreacion: '2024-03-05',
    fechaActualizacion: '2024-11-28',
  },
  // ACCESORIOS - Mochilas
  {
    id: '9',
    nombre: 'Mochila Gym Premium',
    descripcionCorta: 'Mochila espaciosa con compartimento para zapatos',
    descripcionLarga: 'Mochila diseñada específicamente para el gym con múltiples compartimentos, incluyendo uno ventilado para zapatos sucios.',
    categoria: 'Accesorios',
    subcategoria: 'Mochilas',
    tags: ['mochila', 'gym', 'premium'],
    sku: 'MOC-GYM-009',
    imagenes: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500'],
    imagenPrincipal: 0,
    precioRegular: 69.99,
    precioOferta: 59.99,
    porcentajeDescuento: 14,
    stock: 55,
    alertaStockMinimo: 10,
    permitirBackorder: false,
    estado: 'publicado',
    tieneVariantes: false,
    variantes: [],
    requiereEnvio: true,
    peso: 0.8,
    dimensiones: { largo: 50, ancho: 30, alto: 25 },
    tarifaEnvio: 'calculada',
    urlSlug: 'mochila-gym-premium',
    vistas: 890,
    ventas: 67,
    addToCart: 98,
    tasaConversion: 68.4,
    revenueGenerado: 4019.33,
    productosRelacionados: ['8', '10'],
    fechaCreacion: '2024-02-20',
    fechaActualizacion: '2024-12-01',
  },
  {
    id: '10',
    nombre: 'Bolsa Deportiva Duffle',
    descripcionCorta: 'Bolsa de viaje deportiva con correa ajustable',
    descripcionLarga: 'Bolsa duffle versátil perfecta para el gym o viajes cortos. Material resistente al agua.',
    categoria: 'Accesorios',
    subcategoria: 'Mochilas',
    tags: ['bolsa', 'duffle', 'deportiva'],
    sku: 'BOL-DUF-010',
    imagenes: ['https://images.unsplash.com/photo-1547949003-9792a18a2601?w=500'],
    imagenPrincipal: 0,
    precioRegular: 49.99,
    stock: 75,
    alertaStockMinimo: 15,
    permitirBackorder: true,
    estado: 'publicado',
    tieneVariantes: true,
    variantes: [
      { id: 'v21', color: 'Negro', sku: 'BOL-DUF-010-NEG', stock: 40 },
      { id: 'v22', color: 'Azul Marino', sku: 'BOL-DUF-010-AZU', stock: 35 },
    ],
    requiereEnvio: true,
    peso: 0.6,
    tarifaEnvio: 'calculada',
    urlSlug: 'bolsa-deportiva-duffle',
    vistas: 567,
    ventas: 54,
    addToCart: 78,
    tasaConversion: 69.2,
    revenueGenerado: 2699.46,
    productosRelacionados: ['9', '11'],
    fechaCreacion: '2024-03-10',
    fechaActualizacion: '2024-11-29',
  },
  // EQUIPO - Mancuernas
  {
    id: '11',
    nombre: 'Set Mancuernas Ajustables 20kg',
    descripcionCorta: 'Par de mancuernas ajustables de 2.5kg a 20kg',
    descripcionLarga: 'Set completo de mancuernas con peso ajustable. Perfecto para entrenamientos en casa. Incluye estuche de almacenamiento.',
    categoria: 'Equipo',
    subcategoria: 'Mancuernas',
    tags: ['mancuernas', 'ajustables', 'pesas'],
    sku: 'MAN-ADJ-011',
    imagenes: ['https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=500'],
    imagenPrincipal: 0,
    precioRegular: 149.99,
    precioOferta: 129.99,
    porcentajeDescuento: 13,
    stock: 35,
    alertaStockMinimo: 5,
    permitirBackorder: false,
    estado: 'publicado',
    tieneVariantes: false,
    variantes: [],
    requiereEnvio: true,
    peso: 20,
    dimensiones: { largo: 45, ancho: 30, alto: 15 },
    tarifaEnvio: 'calculada',
    urlSlug: 'set-mancuernas-ajustables-20kg',
    vistas: 1234,
    ventas: 28,
    addToCart: 45,
    tasaConversion: 62.2,
    revenueGenerado: 3639.72,
    productosRelacionados: ['12', '13'],
    fechaCreacion: '2024-01-10',
    fechaActualizacion: '2024-12-02',
  },
  {
    id: '12',
    nombre: 'Mancuernas Hexagonales 5kg (Par)',
    descripcionCorta: 'Par de mancuernas hexagonales de goma',
    descripcionLarga: 'Mancuernas con forma hexagonal que evitan que rueden. Recubrimiento de goma para proteger el suelo.',
    categoria: 'Equipo',
    subcategoria: 'Mancuernas',
    tags: ['mancuernas', 'hexagonales', '5kg'],
    sku: 'MAN-HEX-012',
    imagenes: ['https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500'],
    imagenPrincipal: 0,
    precioRegular: 34.99,
    stock: 89,
    alertaStockMinimo: 15,
    permitirBackorder: true,
    estado: 'publicado',
    tieneVariantes: false,
    variantes: [],
    requiereEnvio: true,
    peso: 10,
    tarifaEnvio: 'calculada',
    urlSlug: 'mancuernas-hexagonales-5kg-par',
    vistas: 678,
    ventas: 67,
    addToCart: 89,
    tasaConversion: 75.3,
    revenueGenerado: 2344.33,
    productosRelacionados: ['11', '13'],
    fechaCreacion: '2024-01-18',
    fechaActualizacion: '2024-11-27',
  },
  // EQUIPO - Bandas
  {
    id: '13',
    nombre: 'Set Bandas Elásticas Resistencia',
    descripcionCorta: 'Kit de 5 bandas con diferentes niveles de resistencia',
    descripcionLarga: 'Set completo de bandas elásticas con 5 niveles de resistencia. Incluye anclajes para puertas y bolsa de transporte.',
    categoria: 'Equipo',
    subcategoria: 'Bandas',
    tags: ['bandas', 'elásticas', 'resistencia'],
    sku: 'BAN-ELA-013',
    imagenes: ['https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=500'],
    imagenPrincipal: 0,
    precioRegular: 39.99,
    precioOferta: 34.99,
    porcentajeDescuento: 13,
    stock: 125,
    alertaStockMinimo: 20,
    permitirBackorder: false,
    estado: 'publicado',
    tieneVariantes: false,
    variantes: [],
    requiereEnvio: true,
    peso: 0.5,
    tarifaEnvio: 'calculada',
    urlSlug: 'set-bandas-elasticas-resistencia',
    vistas: 1456,
    ventas: 178,
    addToCart: 234,
    tasaConversion: 76.1,
    revenueGenerado: 6228.22,
    productosRelacionados: ['11', '14'],
    fechaCreacion: '2024-02-05',
    fechaActualizacion: '2024-12-03',
  },
  {
    id: '14',
    nombre: 'Banda Loop Glúteos',
    descripcionCorta: 'Banda circular para entrenamiento de glúteos',
    descripcionLarga: 'Banda elástica en forma de loop perfecta para ejercicios de glúteos y piernas. Material antideslizante.',
    categoria: 'Equipo',
    subcategoria: 'Bandas',
    tags: ['banda', 'loop', 'glúteos'],
    sku: 'BAN-LOO-014',
    imagenes: ['https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=500'],
    imagenPrincipal: 0,
    precioRegular: 12.99,
    stock: 200,
    alertaStockMinimo: 30,
    permitirBackorder: true,
    estado: 'publicado',
    tieneVariantes: true,
    variantes: [
      { id: 'v23', color: 'Rosa', material: 'Ligera', sku: 'BAN-LOO-014-ROS-LIG', stock: 70 },
      { id: 'v24', color: 'Morado', material: 'Media', sku: 'BAN-LOO-014-MOR-MED', stock: 65 },
      { id: 'v25', color: 'Negro', material: 'Pesada', sku: 'BAN-LOO-014-NEG-PES', stock: 65 },
    ],
    requiereEnvio: true,
    peso: 0.1,
    tarifaEnvio: 'fija',
    urlSlug: 'banda-loop-gluteos',
    vistas: 892,
    ventas: 145,
    addToCart: 198,
    tasaConversion: 73.2,
    revenueGenerado: 1883.55,
    productosRelacionados: ['13', '15'],
    fechaCreacion: '2024-02-12',
    fechaActualizacion: '2024-12-01',
  },
  // EQUIPO - Esterillas
  {
    id: '15',
    nombre: 'Esterilla Yoga Premium 6mm',
    descripcionCorta: 'Esterilla antideslizante de alta densidad',
    descripcionLarga: 'Esterilla de yoga profesional con 6mm de grosor. Material ecológico y antideslizante. Incluye correa de transporte.',
    categoria: 'Equipo',
    subcategoria: 'Esterillas',
    tags: ['esterilla', 'yoga', 'premium'],
    sku: 'EST-YOG-015',
    imagenes: ['https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=500'],
    imagenPrincipal: 0,
    precioRegular: 44.99,
    precioOferta: 39.99,
    porcentajeDescuento: 11,
    stock: 95,
    alertaStockMinimo: 15,
    permitirBackorder: false,
    estado: 'publicado',
    tieneVariantes: true,
    variantes: [
      { id: 'v26', color: 'Azul', sku: 'EST-YOG-015-AZU', stock: 35 },
      { id: 'v27', color: 'Morado', sku: 'EST-YOG-015-MOR', stock: 30 },
      { id: 'v28', color: 'Verde', sku: 'EST-YOG-015-VER', stock: 30 },
    ],
    requiereEnvio: true,
    peso: 1.2,
    dimensiones: { largo: 180, ancho: 10, alto: 10 },
    tarifaEnvio: 'calculada',
    urlSlug: 'esterilla-yoga-premium-6mm',
    vistas: 1023,
    ventas: 112,
    addToCart: 167,
    tasaConversion: 67.1,
    revenueGenerado: 4478.88,
    productosRelacionados: ['14', '16'],
    fechaCreacion: '2024-01-22',
    fechaActualizacion: '2024-12-02',
  },
  {
    id: '16',
    nombre: 'Mat Ejercicio Plegable XXL',
    descripcionCorta: 'Colchoneta extra grande plegable para ejercicios',
    descripcionLarga: 'Colchoneta de 200x100cm perfecta para ejercicios de suelo. Se pliega en 4 partes para fácil almacenamiento.',
    categoria: 'Equipo',
    subcategoria: 'Esterillas',
    tags: ['mat', 'plegable', 'xxl'],
    sku: 'MAT-EJE-016',
    imagenes: ['https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=500'],
    imagenPrincipal: 0,
    precioRegular: 79.99,
    stock: 3,
    alertaStockMinimo: 5,
    permitirBackorder: true,
    estado: 'publicado',
    tieneVariantes: false,
    variantes: [],
    requiereEnvio: true,
    peso: 3.5,
    dimensiones: { largo: 200, ancho: 100, alto: 5 },
    tarifaEnvio: 'calculada',
    urlSlug: 'mat-ejercicio-plegable-xxl',
    vistas: 456,
    ventas: 34,
    addToCart: 56,
    tasaConversion: 60.7,
    revenueGenerado: 2719.66,
    productosRelacionados: ['15', '17'],
    fechaCreacion: '2024-03-01',
    fechaActualizacion: '2024-11-30',
  },
  // DIGITAL - eBooks
  {
    id: '17',
    nombre: 'eBook: Guía Completa de Nutrición',
    descripcionCorta: 'Guía digital de 150 páginas sobre nutrición deportiva',
    descripcionLarga: 'eBook completo con todo lo que necesitas saber sobre nutrición deportiva, incluyendo planes de comidas y recetas.',
    categoria: 'Digital',
    subcategoria: 'eBooks',
    tags: ['ebook', 'nutrición', 'guía'],
    sku: 'EBO-NUT-017',
    imagenes: ['https://images.unsplash.com/photo-1532012197267-da84d127e765?w=500'],
    imagenPrincipal: 0,
    precioRegular: 19.99,
    precioOferta: 14.99,
    porcentajeDescuento: 25,
    stock: 9999,
    alertaStockMinimo: 0,
    permitirBackorder: true,
    estado: 'publicado',
    tieneVariantes: false,
    variantes: [],
    requiereEnvio: false,
    urlSlug: 'ebook-guia-completa-nutricion',
    vistas: 2345,
    ventas: 234,
    addToCart: 312,
    tasaConversion: 75.0,
    revenueGenerado: 3507.66,
    productosRelacionados: ['18', '19'],
    fechaCreacion: '2024-01-05',
    fechaActualizacion: '2024-12-03',
  },
  {
    id: '18',
    nombre: 'eBook: Entrenamiento en Casa',
    descripcionCorta: 'Programa de entrenamiento sin equipo necesario',
    descripcionLarga: 'eBook con rutinas completas para entrenar en casa sin necesidad de equipo especial. Incluye videos.',
    categoria: 'Digital',
    subcategoria: 'eBooks',
    tags: ['ebook', 'entrenamiento', 'casa'],
    sku: 'EBO-ENT-018',
    imagenes: ['https://images.unsplash.com/photo-1512941675424-1c3c6c2c95c8?w=500'],
    imagenPrincipal: 0,
    precioRegular: 24.99,
    stock: 9999,
    alertaStockMinimo: 0,
    permitirBackorder: true,
    estado: 'publicado',
    tieneVariantes: false,
    variantes: [],
    requiereEnvio: false,
    urlSlug: 'ebook-entrenamiento-en-casa',
    vistas: 1890,
    ventas: 189,
    addToCart: 245,
    tasaConversion: 77.1,
    revenueGenerado: 4723.11,
    productosRelacionados: ['17', '19'],
    fechaCreacion: '2024-01-12',
    fechaActualizacion: '2024-11-29',
  },
  // DIGITAL - Programas
  {
    id: '19',
    nombre: 'Programa: 12 Semanas Transformación',
    descripcionCorta: 'Programa completo de 12 semanas con seguimiento',
    descripcionLarga: 'Programa digital completo de transformación física. Incluye rutinas de ejercicio, plan nutricional y acceso a comunidad privada.',
    categoria: 'Digital',
    subcategoria: 'Programas',
    tags: ['programa', 'transformación', '12semanas'],
    sku: 'PRO-TRA-019',
    imagenes: ['https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=500'],
    imagenPrincipal: 0,
    precioRegular: 199.99,
    precioOferta: 149.99,
    porcentajeDescuento: 25,
    stock: 9999,
    alertaStockMinimo: 0,
    permitirBackorder: true,
    estado: 'publicado',
    tieneVariantes: false,
    variantes: [],
    requiereEnvio: false,
    urlSlug: 'programa-12-semanas-transformacion',
    vistas: 3456,
    ventas: 156,
    addToCart: 234,
    tasaConversion: 66.7,
    revenueGenerado: 23398.44,
    productosRelacionados: ['17', '18'],
    fechaCreacion: '2024-01-01',
    fechaActualizacion: '2024-12-04',
  },
  {
    id: '20',
    nombre: 'Programa: Preparación Media Maratón',
    descripcionCorta: 'Plan de entrenamiento de 16 semanas para media maratón',
    descripcionLarga: 'Programa especializado para preparar tu primera media maratón o mejorar tu marca personal.',
    categoria: 'Digital',
    subcategoria: 'Programas',
    tags: ['programa', 'running', 'media maratón'],
    sku: 'PRO-MAR-020',
    imagenes: ['https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=500'],
    imagenPrincipal: 0,
    precioRegular: 89.99,
    stock: 9999,
    alertaStockMinimo: 0,
    permitirBackorder: true,
    estado: 'programado',
    tieneVariantes: false,
    variantes: [],
    requiereEnvio: false,
    urlSlug: 'programa-preparacion-media-maraton',
    vistas: 678,
    ventas: 45,
    addToCart: 78,
    tasaConversion: 57.7,
    revenueGenerado: 4049.55,
    productosRelacionados: ['5', '8'],
    fechaCreacion: '2024-03-15',
    fechaActualizacion: '2024-11-28',
  },
  // Productos adicionales para completar 50
  {
    id: '21',
    nombre: 'Leggings Deportivos Mujer',
    descripcionCorta: 'Leggings de compresión con cintura alta',
    descripcionLarga: 'Leggings de alta compresión perfectos para cualquier tipo de entrenamiento. Tejido que absorbe el sudor.',
    categoria: 'Ropa',
    subcategoria: 'Pantalones',
    tags: ['leggings', 'mujer', 'compresión'],
    sku: 'LEG-DEP-021',
    imagenes: ['https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=500'],
    imagenPrincipal: 0,
    precioRegular: 39.99,
    precioOferta: 34.99,
    porcentajeDescuento: 13,
    stock: 165,
    alertaStockMinimo: 25,
    permitirBackorder: false,
    estado: 'publicado',
    tieneVariantes: true,
    variantes: [
      { id: 'v29', talla: 'XS', color: 'Negro', sku: 'LEG-DEP-021-XS-NEG', stock: 40 },
      { id: 'v30', talla: 'S', color: 'Negro', sku: 'LEG-DEP-021-S-NEG', stock: 45 },
      { id: 'v31', talla: 'M', color: 'Gris', sku: 'LEG-DEP-021-M-GRI', stock: 40 },
      { id: 'v32', talla: 'L', color: 'Gris', sku: 'LEG-DEP-021-L-GRI', stock: 40 },
    ],
    requiereEnvio: true,
    peso: 0.25,
    tarifaEnvio: 'calculada',
    urlSlug: 'leggings-deportivos-mujer',
    vistas: 1567,
    ventas: 203,
    addToCart: 278,
    tasaConversion: 73.0,
    revenueGenerado: 7102.97,
    productosRelacionados: ['4', '22'],
    fechaCreacion: '2024-01-18',
    fechaActualizacion: '2024-12-02',
  },
  {
    id: '22',
    nombre: 'Top Deportivo Mujer',
    descripcionCorta: 'Top deportivo con soporte medio',
    descripcionLarga: 'Top deportivo con soporte medio ideal para running, fitness y yoga. Diseño cruzado en la espalda.',
    categoria: 'Ropa',
    subcategoria: 'Tops',
    tags: ['top', 'mujer', 'deportivo'],
    sku: 'TOP-DEP-022',
    imagenes: ['https://images.unsplash.com/photo-1601422407692-ec4eeec1d9b3?w=500'],
    imagenPrincipal: 0,
    precioRegular: 29.99,
    stock: 145,
    alertaStockMinimo: 20,
    permitirBackorder: false,
    estado: 'publicado',
    tieneVariantes: true,
    variantes: [
      { id: 'v33', talla: 'XS', color: 'Rosa', sku: 'TOP-DEP-022-XS-ROS', stock: 35 },
      { id: 'v34', talla: 'S', color: 'Rosa', sku: 'TOP-DEP-022-S-ROS', stock: 40 },
      { id: 'v35', talla: 'M', color: 'Negro', sku: 'TOP-DEP-022-M-NEG', stock: 35 },
      { id: 'v36', talla: 'L', color: 'Negro', sku: 'TOP-DEP-022-L-NEG', stock: 35 },
    ],
    requiereEnvio: true,
    peso: 0.15,
    tarifaEnvio: 'calculada',
    urlSlug: 'top-deportivo-mujer',
    vistas: 1234,
    ventas: 167,
    addToCart: 223,
    tasaConversion: 74.9,
    revenueGenerado: 5008.33,
    productosRelacionados: ['21', '4'],
    fechaCreacion: '2024-02-01',
    fechaActualizacion: '2024-12-01',
  },
  {
    id: '23',
    nombre: 'Pantalón Jogger Hombre',
    descripcionCorta: 'Pantalón jogger cómodo para entrenamiento',
    descripcionLarga: 'Pantalón jogger con bolsillos con cierre y ajuste en tobillo. Perfecto para calentamiento y uso casual.',
    categoria: 'Ropa',
    subcategoria: 'Pantalones',
    tags: ['jogger', 'hombre', 'casual'],
    sku: 'PAN-JOG-023',
    imagenes: ['https://images.unsplash.com/photo-1552902876-2f2d45c8b861?w=500'],
    imagenPrincipal: 0,
    precioRegular: 49.99,
    stock: 98,
    alertaStockMinimo: 15,
    permitirBackorder: true,
    estado: 'publicado',
    tieneVariantes: true,
    variantes: [
      { id: 'v37', talla: 'M', color: 'Gris', sku: 'PAN-JOG-023-M-GRI', stock: 30 },
      { id: 'v38', talla: 'L', color: 'Gris', sku: 'PAN-JOG-023-L-GRI', stock: 35 },
      { id: 'v39', talla: 'XL', color: 'Negro', sku: 'PAN-JOG-023-XL-NEG', stock: 33 },
    ],
    requiereEnvio: true,
    peso: 0.4,
    tarifaEnvio: 'calculada',
    urlSlug: 'pantalon-jogger-hombre',
    vistas: 789,
    ventas: 89,
    addToCart: 123,
    tasaConversion: 72.4,
    revenueGenerado: 4449.11,
    productosRelacionados: ['1', '3'],
    fechaCreacion: '2024-02-08',
    fechaActualizacion: '2024-11-30',
  },
  {
    id: '24',
    nombre: 'Shorts Running Hombre',
    descripcionCorta: 'Shorts ligeros con bolsillo interior para llaves',
    descripcionLarga: 'Shorts de running ultra ligeros con tecnología anti-roce. Incluye bolsillo interior con cierre.',
    categoria: 'Ropa',
    subcategoria: 'Pantalones',
    tags: ['shorts', 'running', 'hombre'],
    sku: 'SHO-RUN-024',
    imagenes: ['https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=500'],
    imagenPrincipal: 0,
    precioRegular: 34.99,
    stock: 120,
    alertaStockMinimo: 20,
    permitirBackorder: false,
    estado: 'publicado',
    tieneVariantes: true,
    variantes: [
      { id: 'v40', talla: 'S', color: 'Azul', sku: 'SHO-RUN-024-S-AZU', stock: 30 },
      { id: 'v41', talla: 'M', color: 'Azul', sku: 'SHO-RUN-024-M-AZU', stock: 40 },
      { id: 'v42', talla: 'L', color: 'Negro', sku: 'SHO-RUN-024-L-NEG', stock: 50 },
    ],
    requiereEnvio: true,
    peso: 0.15,
    tarifaEnvio: 'calculada',
    urlSlug: 'shorts-running-hombre',
    vistas: 890,
    ventas: 134,
    addToCart: 178,
    tasaConversion: 75.3,
    revenueGenerado: 4688.66,
    productosRelacionados: ['1', '5'],
    fechaCreacion: '2024-02-15',
    fechaActualizacion: '2024-12-02',
  },
  {
    id: '25',
    nombre: 'Calcetines Deportivos Pack 3',
    descripcionCorta: 'Pack de 3 pares de calcetines técnicos',
    descripcionLarga: 'Calcetines de compresión media con refuerzo en talón y puntera. Perfectos para cualquier deporte.',
    categoria: 'Ropa',
    subcategoria: 'Calcetines',
    tags: ['calcetines', 'pack', 'técnicos'],
    sku: 'CAL-TEC-025',
    imagenes: ['https://images.unsplash.com/photo-1586350977974-e5f9a56c62f3?w=500'],
    imagenPrincipal: 0,
    precioRegular: 19.99,
    stock: 250,
    alertaStockMinimo: 40,
    permitirBackorder: true,
    estado: 'publicado',
    tieneVariantes: true,
    variantes: [
      { id: 'v43', talla: 'M', color: 'Blanco', sku: 'CAL-TEC-025-M-BLA', stock: 90 },
      { id: 'v44', talla: 'L', color: 'Blanco', sku: 'CAL-TEC-025-L-BLA', stock: 80 },
      { id: 'v45', talla: 'M', color: 'Negro', sku: 'CAL-TEC-025-M-NEG', stock: 80 },
    ],
    requiereEnvio: true,
    peso: 0.15,
    tarifaEnvio: 'fija',
    urlSlug: 'calcetines-deportivos-pack-3',
    vistas: 567,
    ventas: 234,
    addToCart: 289,
    tasaConversion: 81.0,
    revenueGenerado: 4677.66,
    productosRelacionados: ['1', '24'],
    fechaCreacion: '2024-03-01',
    fechaActualizacion: '2024-12-03',
  },
  {
    id: '26',
    nombre: 'Chaleco Reflectante Running',
    descripcionCorta: 'Chaleco ligero con elementos reflectantes',
    descripcionLarga: 'Chaleco ultra ligero con bandas reflectantes 360°. Perfecto para correr de noche de forma segura.',
    categoria: 'Ropa',
    subcategoria: 'Accesorios',
    tags: ['chaleco', 'reflectante', 'seguridad'],
    sku: 'CHA-REF-026',
    imagenes: ['https://images.unsplash.com/photo-1522441815192-d9f04eb0615c?w=500'],
    imagenPrincipal: 0,
    precioRegular: 24.99,
    stock: 78,
    alertaStockMinimo: 15,
    permitirBackorder: false,
    estado: 'publicado',
    tieneVariantes: false,
    variantes: [],
    requiereEnvio: true,
    peso: 0.1,
    tarifaEnvio: 'fija',
    urlSlug: 'chaleco-reflectante-running',
    vistas: 456,
    ventas: 56,
    addToCart: 89,
    tasaConversion: 62.9,
    revenueGenerado: 1399.44,
    productosRelacionados: ['24', '5'],
    fechaCreacion: '2024-03-05',
    fechaActualizacion: '2024-11-28',
  },
  {
    id: '27',
    nombre: 'Guantes Gimnasio Acolchados',
    descripcionCorta: 'Guantes con acolchado extra para levantamiento',
    descripcionLarga: 'Guantes con protección acolchada en palma y muñequera de soporte. Perfectos para levantamiento de pesas.',
    categoria: 'Accesorios',
    subcategoria: 'Protección',
    tags: ['guantes', 'gimnasio', 'levantamiento'],
    sku: 'GUA-GYM-027',
    imagenes: ['https://images.unsplash.com/photo-1597452485669-2c7bb5fef90d?w=500'],
    imagenPrincipal: 0,
    precioRegular: 24.99,
    stock: 115,
    alertaStockMinimo: 20,
    permitirBackorder: false,
    estado: 'publicado',
    tieneVariantes: true,
    variantes: [
      { id: 'v46', talla: 'S', color: 'Negro', sku: 'GUA-GYM-027-S-NEG', stock: 30 },
      { id: 'v47', talla: 'M', color: 'Negro', sku: 'GUA-GYM-027-M-NEG', stock: 45 },
      { id: 'v48', talla: 'L', color: 'Negro', sku: 'GUA-GYM-027-L-NEG', stock: 40 },
    ],
    requiereEnvio: true,
    peso: 0.15,
    tarifaEnvio: 'fija',
    urlSlug: 'guantes-gimnasio-acolchados',
    vistas: 678,
    ventas: 89,
    addToCart: 123,
    tasaConversion: 72.4,
    revenueGenerado: 2224.11,
    productosRelacionados: ['11', '12'],
    fechaCreacion: '2024-02-20',
    fechaActualizacion: '2024-12-01',
  },
  {
    id: '28',
    nombre: 'Cinturón Lumbar Levantamiento',
    descripcionCorta: 'Cinturón de soporte lumbar con hebilla',
    descripcionLarga: 'Cinturón lumbar de 10cm de ancho para levantamientos pesados. Material resistente con hebilla de doble cierre.',
    categoria: 'Accesorios',
    subcategoria: 'Protección',
    tags: ['cinturón', 'lumbar', 'powerlifting'],
    sku: 'CIN-LUM-028',
    imagenes: ['https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500'],
    imagenPrincipal: 0,
    precioRegular: 49.99,
    stock: 65,
    alertaStockMinimo: 10,
    permitirBackorder: true,
    estado: 'publicado',
    tieneVariantes: true,
    variantes: [
      { id: 'v49', talla: 'M', sku: 'CIN-LUM-028-M', stock: 20 },
      { id: 'v50', talla: 'L', sku: 'CIN-LUM-028-L', stock: 25 },
      { id: 'v51', talla: 'XL', sku: 'CIN-LUM-028-XL', stock: 20 },
    ],
    requiereEnvio: true,
    peso: 0.5,
    tarifaEnvio: 'calculada',
    urlSlug: 'cinturon-lumbar-levantamiento',
    vistas: 890,
    ventas: 67,
    addToCart: 98,
    tasaConversion: 68.4,
    revenueGenerado: 3349.33,
    productosRelacionados: ['11', '27'],
    fechaCreacion: '2024-02-25',
    fechaActualizacion: '2024-11-29',
  },
  {
    id: '29',
    nombre: 'Muñequeras Elásticas Soporte',
    descripcionCorta: 'Par de muñequeras con cierre velcro',
    descripcionLarga: 'Muñequeras elásticas con soporte ajustable mediante velcro. Perfectas para press y ejercicios de push.',
    categoria: 'Accesorios',
    subcategoria: 'Protección',
    tags: ['muñequeras', 'soporte', 'velcro'],
    sku: 'MUÑ-ELA-029',
    imagenes: ['https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=500'],
    imagenPrincipal: 0,
    precioRegular: 14.99,
    stock: 156,
    alertaStockMinimo: 25,
    permitirBackorder: false,
    estado: 'publicado',
    tieneVariantes: false,
    variantes: [],
    requiereEnvio: true,
    peso: 0.1,
    tarifaEnvio: 'fija',
    urlSlug: 'munequeras-elasticas-soporte',
    vistas: 567,
    ventas: 123,
    addToCart: 167,
    tasaConversion: 73.7,
    revenueGenerado: 1843.77,
    productosRelacionados: ['27', '28'],
    fechaCreacion: '2024-03-08',
    fechaActualizacion: '2024-12-02',
  },
  {
    id: '30',
    nombre: 'Suplemento Proteína Whey 1kg',
    descripcionCorta: 'Proteína whey aislada sabor chocolate',
    descripcionLarga: 'Proteína de suero de leche de alta calidad con 25g de proteína por servicio. Sabor chocolate cremoso.',
    categoria: 'Accesorios',
    subcategoria: 'Suplementos',
    tags: ['proteína', 'whey', 'suplemento'],
    sku: 'SUP-PRO-030',
    imagenes: ['https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=500'],
    imagenPrincipal: 0,
    precioRegular: 39.99,
    precioOferta: 34.99,
    porcentajeDescuento: 13,
    stock: 0,
    alertaStockMinimo: 10,
    permitirBackorder: true,
    estado: 'agotado',
    tieneVariantes: true,
    variantes: [
      { id: 'v52', color: 'Chocolate', sku: 'SUP-PRO-030-CHO', stock: 0 },
      { id: 'v53', color: 'Vainilla', sku: 'SUP-PRO-030-VAI', stock: 0 },
    ],
    requiereEnvio: true,
    peso: 1.2,
    tarifaEnvio: 'calculada',
    urlSlug: 'suplemento-proteina-whey-1kg',
    vistas: 2345,
    ventas: 289,
    addToCart: 378,
    tasaConversion: 76.5,
    revenueGenerado: 10111.11,
    productosRelacionados: ['7', '31'],
    fechaCreacion: '2024-01-08',
    fechaActualizacion: '2024-12-04',
  },
  {
    id: '31',
    nombre: 'Creatina Monohidrato 300g',
    descripcionCorta: 'Creatina pura micronizada sin sabor',
    descripcionLarga: 'Creatina monohidrato 100% pura, micronizada para mejor absorción. Sin sabor, perfecta para mezclar.',
    categoria: 'Accesorios',
    subcategoria: 'Suplementos',
    tags: ['creatina', 'suplemento', 'fuerza'],
    sku: 'SUP-CRE-031',
    imagenes: ['https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=500'],
    imagenPrincipal: 0,
    precioRegular: 24.99,
    stock: 145,
    alertaStockMinimo: 20,
    permitirBackorder: false,
    estado: 'publicado',
    tieneVariantes: false,
    variantes: [],
    requiereEnvio: true,
    peso: 0.35,
    tarifaEnvio: 'calculada',
    urlSlug: 'creatina-monohidrato-300g',
    vistas: 1456,
    ventas: 178,
    addToCart: 234,
    tasaConversion: 76.1,
    revenueGenerado: 4448.22,
    productosRelacionados: ['30', '7'],
    fechaCreacion: '2024-01-15',
    fechaActualizacion: '2024-12-02',
  },
  {
    id: '32',
    nombre: 'Barritas Proteicas Pack 12',
    descripcionCorta: 'Pack de 12 barritas con 20g de proteína',
    descripcionLarga: 'Barritas proteicas con 20g de proteína y solo 2g de azúcar. Sabor chocolate y caramelo.',
    categoria: 'Accesorios',
    subcategoria: 'Suplementos',
    tags: ['barritas', 'proteína', 'snack'],
    sku: 'SUP-BAR-032',
    imagenes: ['https://images.unsplash.com/photo-1582735689369-4fe89db7114c?w=500'],
    imagenPrincipal: 0,
    precioRegular: 29.99,
    stock: 89,
    alertaStockMinimo: 15,
    permitirBackorder: true,
    estado: 'publicado',
    tieneVariantes: false,
    variantes: [],
    requiereEnvio: true,
    peso: 0.6,
    tarifaEnvio: 'calculada',
    urlSlug: 'barritas-proteicas-pack-12',
    vistas: 890,
    ventas: 156,
    addToCart: 198,
    tasaConversion: 78.8,
    revenueGenerado: 4678.44,
    productosRelacionados: ['30', '31'],
    fechaCreacion: '2024-02-01',
    fechaActualizacion: '2024-12-01',
  },
  {
    id: '33',
    nombre: 'Rodillo Foam Masaje',
    descripcionCorta: 'Rodillo de espuma para auto-masaje',
    descripcionLarga: 'Rodillo de espuma de alta densidad para masaje miofascial y recuperación muscular. 33cm de longitud.',
    categoria: 'Equipo',
    subcategoria: 'Recuperación',
    tags: ['rodillo', 'foam', 'masaje'],
    sku: 'EQU-ROD-033',
    imagenes: ['https://images.unsplash.com/photo-1599058917212-d750089bc07e?w=500'],
    imagenPrincipal: 0,
    precioRegular: 24.99,
    stock: 134,
    alertaStockMinimo: 20,
    permitirBackorder: false,
    estado: 'publicado',
    tieneVariantes: true,
    variantes: [
      { id: 'v54', color: 'Negro', sku: 'EQU-ROD-033-NEG', stock: 50 },
      { id: 'v55', color: 'Azul', sku: 'EQU-ROD-033-AZU', stock: 44 },
      { id: 'v56', color: 'Rosa', sku: 'EQU-ROD-033-ROS', stock: 40 },
    ],
    requiereEnvio: true,
    peso: 0.8,
    dimensiones: { largo: 33, ancho: 15, alto: 15 },
    tarifaEnvio: 'calculada',
    urlSlug: 'rodillo-foam-masaje',
    vistas: 789,
    ventas: 112,
    addToCart: 156,
    tasaConversion: 71.8,
    revenueGenerado: 2798.88,
    productosRelacionados: ['34', '35'],
    fechaCreacion: '2024-02-10',
    fechaActualizacion: '2024-11-30',
  },
  {
    id: '34',
    nombre: 'Pelota Masaje Lacrosse',
    descripcionCorta: 'Pelota de caucho para puntos de presión',
    descripcionLarga: 'Pelota de masaje tipo lacrosse perfecta para trabajar puntos de presión específicos. Caucho de alta densidad.',
    categoria: 'Equipo',
    subcategoria: 'Recuperación',
    tags: ['pelota', 'masaje', 'lacrosse'],
    sku: 'EQU-PEL-034',
    imagenes: ['https://images.unsplash.com/photo-1598971639058-fab3c3109a3b?w=500'],
    imagenPrincipal: 0,
    precioRegular: 9.99,
    stock: 200,
    alertaStockMinimo: 30,
    permitirBackorder: true,
    estado: 'publicado',
    tieneVariantes: false,
    variantes: [],
    requiereEnvio: true,
    peso: 0.15,
    tarifaEnvio: 'fija',
    urlSlug: 'pelota-masaje-lacrosse',
    vistas: 456,
    ventas: 167,
    addToCart: 212,
    tasaConversion: 78.8,
    revenueGenerado: 1668.33,
    productosRelacionados: ['33', '35'],
    fechaCreacion: '2024-02-18',
    fechaActualizacion: '2024-12-02',
  },
  {
    id: '35',
    nombre: 'Pistola Masaje Muscular',
    descripcionCorta: 'Pistola de masaje profesional con 6 velocidades',
    descripcionLarga: 'Pistola de masaje muscular de percusión con 6 niveles de velocidad y 4 cabezales intercambiables. Batería de larga duración.',
    categoria: 'Equipo',
    subcategoria: 'Recuperación',
    tags: ['pistola', 'masaje', 'percusión'],
    sku: 'EQU-PIS-035',
    imagenes: ['https://images.unsplash.com/photo-1590650516494-0c8e4a4dd67e?w=500'],
    imagenPrincipal: 0,
    precioRegular: 149.99,
    precioOferta: 119.99,
    porcentajeDescuento: 20,
    stock: 2,
    alertaStockMinimo: 5,
    permitirBackorder: true,
    estado: 'publicado',
    tieneVariantes: false,
    variantes: [],
    requiereEnvio: true,
    peso: 1.5,
    dimensiones: { largo: 25, ancho: 20, alto: 10 },
    tarifaEnvio: 'calculada',
    urlSlug: 'pistola-masaje-muscular',
    vistas: 2345,
    ventas: 78,
    addToCart: 123,
    tasaConversion: 63.4,
    revenueGenerado: 9359.22,
    productosRelacionados: ['33', '34'],
    fechaCreacion: '2024-01-12',
    fechaActualizacion: '2024-12-03',
  },
  {
    id: '36',
    nombre: 'Cuerda Saltar Velocidad',
    descripcionCorta: 'Cuerda de velocidad con rodamientos',
    descripcionLarga: 'Cuerda para saltar profesional con rodamientos de bolas para giros ultra rápidos. Mangos ergonómicos.',
    categoria: 'Equipo',
    subcategoria: 'Cardio',
    tags: ['cuerda', 'saltar', 'velocidad'],
    sku: 'EQU-CUE-036',
    imagenes: ['https://images.unsplash.com/photo-1598971639058-fab3c3109a3b?w=500'],
    imagenPrincipal: 0,
    precioRegular: 19.99,
    stock: 178,
    alertaStockMinimo: 25,
    permitirBackorder: false,
    estado: 'publicado',
    tieneVariantes: false,
    variantes: [],
    requiereEnvio: true,
    peso: 0.2,
    tarifaEnvio: 'fija',
    urlSlug: 'cuerda-saltar-velocidad',
    vistas: 890,
    ventas: 145,
    addToCart: 189,
    tasaConversion: 76.7,
    revenueGenerado: 2898.55,
    productosRelacionados: ['24', '37'],
    fechaCreacion: '2024-02-22',
    fechaActualizacion: '2024-12-01',
  },
  {
    id: '37',
    nombre: 'Kettlebell 12kg',
    descripcionCorta: 'Pesa rusa de hierro fundido con recubrimiento',
    descripcionLarga: 'Kettlebell de 12kg con recubrimiento de vinilo para protección del suelo. Mango ergonómico.',
    categoria: 'Equipo',
    subcategoria: 'Pesas',
    tags: ['kettlebell', 'pesa', '12kg'],
    sku: 'EQU-KET-037',
    imagenes: ['https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=500'],
    imagenPrincipal: 0,
    precioRegular: 44.99,
    stock: 67,
    alertaStockMinimo: 10,
    permitirBackorder: false,
    estado: 'publicado',
    tieneVariantes: false,
    variantes: [],
    requiereEnvio: true,
    peso: 12,
    dimensiones: { largo: 25, ancho: 20, alto: 28 },
    tarifaEnvio: 'calculada',
    urlSlug: 'kettlebell-12kg',
    vistas: 678,
    ventas: 89,
    addToCart: 112,
    tasaConversion: 79.5,
    revenueGenerado: 4004.11,
    productosRelacionados: ['11', '12'],
    fechaCreacion: '2024-02-05',
    fechaActualizacion: '2024-11-28',
  },
  {
    id: '38',
    nombre: 'Balón Medicinal 5kg',
    descripcionCorta: 'Balón medicinal con superficie antideslizante',
    descripcionLarga: 'Balón medicinal de 5kg con textura rugosa para mejor agarre. Perfecto para ejercicios funcionales.',
    categoria: 'Equipo',
    subcategoria: 'Pesas',
    tags: ['balón', 'medicinal', '5kg'],
    sku: 'EQU-BAL-038',
    imagenes: ['https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=500'],
    imagenPrincipal: 0,
    precioRegular: 34.99,
    stock: 89,
    alertaStockMinimo: 15,
    permitirBackorder: true,
    estado: 'publicado',
    tieneVariantes: false,
    variantes: [],
    requiereEnvio: true,
    peso: 5,
    tarifaEnvio: 'calculada',
    urlSlug: 'balon-medicinal-5kg',
    vistas: 567,
    ventas: 78,
    addToCart: 98,
    tasaConversion: 79.6,
    revenueGenerado: 2729.22,
    productosRelacionados: ['37', '11'],
    fechaCreacion: '2024-03-01',
    fechaActualizacion: '2024-11-30',
  },
  {
    id: '39',
    nombre: 'Discos Deslizantes Core',
    descripcionCorta: 'Par de discos deslizantes para ejercicios',
    descripcionLarga: 'Discos deslizantes de doble cara para alfombra y suelo duro. Perfectos para ejercicios de core y HIIT.',
    categoria: 'Equipo',
    subcategoria: 'Accesorios',
    tags: ['discos', 'deslizantes', 'core'],
    sku: 'EQU-DIS-039',
    imagenes: ['https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=500'],
    imagenPrincipal: 0,
    precioRegular: 14.99,
    stock: 156,
    alertaStockMinimo: 25,
    permitirBackorder: false,
    estado: 'publicado',
    tieneVariantes: false,
    variantes: [],
    requiereEnvio: true,
    peso: 0.15,
    tarifaEnvio: 'fija',
    urlSlug: 'discos-deslizantes-core',
    vistas: 456,
    ventas: 123,
    addToCart: 156,
    tasaConversion: 78.8,
    revenueGenerado: 1843.77,
    productosRelacionados: ['15', '16'],
    fechaCreacion: '2024-03-05',
    fechaActualizacion: '2024-12-02',
  },
  {
    id: '40',
    nombre: 'TRX Sistema Suspensión Pro',
    descripcionCorta: 'Sistema de entrenamiento en suspensión profesional',
    descripcionLarga: 'TRX Pro con anclaje para puerta, árbol y techo. Incluye guía de ejercicios y bolsa de transporte.',
    categoria: 'Equipo',
    subcategoria: 'Suspensión',
    tags: ['trx', 'suspensión', 'funcional'],
    sku: 'EQU-TRX-040',
    imagenes: ['https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=500'],
    imagenPrincipal: 0,
    precioRegular: 189.99,
    precioOferta: 159.99,
    porcentajeDescuento: 16,
    stock: 45,
    alertaStockMinimo: 8,
    permitirBackorder: false,
    estado: 'publicado',
    tieneVariantes: false,
    variantes: [],
    requiereEnvio: true,
    peso: 1.2,
    dimensiones: { largo: 30, ancho: 25, alto: 10 },
    tarifaEnvio: 'calculada',
    urlSlug: 'trx-sistema-suspension-pro',
    vistas: 1234,
    ventas: 67,
    addToCart: 98,
    tasaConversion: 68.4,
    revenueGenerado: 10719.33,
    productosRelacionados: ['13', '41'],
    fechaCreacion: '2024-01-20',
    fechaActualizacion: '2024-12-01',
  },
  {
    id: '41',
    nombre: 'Barra Dominadas Puerta',
    descripcionCorta: 'Barra extensible para dominadas sin instalación',
    descripcionLarga: 'Barra de dominadas que se instala sin tornillos en el marco de la puerta. Soporta hasta 150kg.',
    categoria: 'Equipo',
    subcategoria: 'Barras',
    tags: ['barra', 'dominadas', 'puerta'],
    sku: 'EQU-BAR-041',
    imagenes: ['https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500'],
    imagenPrincipal: 0,
    precioRegular: 39.99,
    stock: 78,
    alertaStockMinimo: 12,
    permitirBackorder: true,
    estado: 'publicado',
    tieneVariantes: false,
    variantes: [],
    requiereEnvio: true,
    peso: 2.5,
    dimensiones: { largo: 100, ancho: 30, alto: 10 },
    tarifaEnvio: 'calculada',
    urlSlug: 'barra-dominadas-puerta',
    vistas: 890,
    ventas: 89,
    addToCart: 123,
    tasaConversion: 72.4,
    revenueGenerado: 3559.11,
    productosRelacionados: ['40', '42'],
    fechaCreacion: '2024-02-15',
    fechaActualizacion: '2024-11-29',
  },
  {
    id: '42',
    nombre: 'Paralelas Flexiones',
    descripcionCorta: 'Par de barras paralelas para flexiones y L-sits',
    descripcionLarga: 'Paralelas de metal con base antideslizante. Perfectas para flexiones, L-sits y ejercicios de calistenia.',
    categoria: 'Equipo',
    subcategoria: 'Barras',
    tags: ['paralelas', 'flexiones', 'calistenia'],
    sku: 'EQU-PAR-042',
    imagenes: ['https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=500'],
    imagenPrincipal: 0,
    precioRegular: 49.99,
    stock: 56,
    alertaStockMinimo: 10,
    permitirBackorder: false,
    estado: 'publicado',
    tieneVariantes: false,
    variantes: [],
    requiereEnvio: true,
    peso: 3.0,
    dimensiones: { largo: 30, ancho: 25, alto: 15 },
    tarifaEnvio: 'calculada',
    urlSlug: 'paralelas-flexiones',
    vistas: 567,
    ventas: 67,
    addToCart: 89,
    tasaConversion: 75.3,
    revenueGenerado: 3349.33,
    productosRelacionados: ['41', '40'],
    fechaCreacion: '2024-02-28',
    fechaActualizacion: '2024-12-02',
  },
  {
    id: '43',
    nombre: 'Balón Suizo 65cm',
    descripcionCorta: 'Pelota de ejercicio anti-explosión',
    descripcionLarga: 'Balón suizo de 65cm con tecnología anti-explosión. Incluye bomba de inflado y guía de ejercicios.',
    categoria: 'Equipo',
    subcategoria: 'Pelotas',
    tags: ['balón', 'suizo', 'fitball'],
    sku: 'EQU-FIT-043',
    imagenes: ['https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=500'],
    imagenPrincipal: 0,
    precioRegular: 29.99,
    stock: 112,
    alertaStockMinimo: 20,
    permitirBackorder: false,
    estado: 'publicado',
    tieneVariantes: true,
    variantes: [
      { id: 'v57', color: 'Azul', sku: 'EQU-FIT-043-AZU', stock: 40 },
      { id: 'v58', color: 'Gris', sku: 'EQU-FIT-043-GRI', stock: 37 },
      { id: 'v59', color: 'Rosa', sku: 'EQU-FIT-043-ROS', stock: 35 },
    ],
    requiereEnvio: true,
    peso: 1.0,
    tarifaEnvio: 'calculada',
    urlSlug: 'balon-suizo-65cm',
    vistas: 789,
    ventas: 98,
    addToCart: 134,
    tasaConversion: 73.1,
    revenueGenerado: 2939.02,
    productosRelacionados: ['15', '38'],
    fechaCreacion: '2024-02-12',
    fechaActualizacion: '2024-12-01',
  },
  {
    id: '44',
    nombre: 'Reloj Deportivo GPS',
    descripcionCorta: 'Smartwatch deportivo con GPS y monitor cardíaco',
    descripcionLarga: 'Reloj deportivo con GPS integrado, monitor de frecuencia cardíaca, resistencia al agua y batería de 7 días.',
    categoria: 'Accesorios',
    subcategoria: 'Tecnología',
    tags: ['reloj', 'gps', 'smartwatch'],
    sku: 'TEC-REL-044',
    imagenes: ['https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=500'],
    imagenPrincipal: 0,
    precioRegular: 199.99,
    precioOferta: 169.99,
    porcentajeDescuento: 15,
    stock: 34,
    alertaStockMinimo: 8,
    permitirBackorder: false,
    estado: 'publicado',
    tieneVariantes: true,
    variantes: [
      { id: 'v60', color: 'Negro', sku: 'TEC-REL-044-NEG', stock: 20 },
      { id: 'v61', color: 'Azul', sku: 'TEC-REL-044-AZU', stock: 14 },
    ],
    requiereEnvio: true,
    peso: 0.2,
    tarifaEnvio: 'calculada',
    urlSlug: 'reloj-deportivo-gps',
    vistas: 2345,
    ventas: 67,
    addToCart: 123,
    tasaConversion: 54.5,
    revenueGenerado: 11389.33,
    productosRelacionados: ['45', '24'],
    fechaCreacion: '2024-01-15',
    fechaActualizacion: '2024-12-03',
  },
  {
    id: '45',
    nombre: 'Auriculares Deportivos Bluetooth',
    descripcionCorta: 'Auriculares inalámbricos resistentes al sudor',
    descripcionLarga: 'Auriculares deportivos true wireless con cancelación de ruido, IPX7 resistentes al agua y 8h de batería.',
    categoria: 'Accesorios',
    subcategoria: 'Tecnología',
    tags: ['auriculares', 'bluetooth', 'deportivos'],
    sku: 'TEC-AUR-045',
    imagenes: ['https://images.unsplash.com/photo-1590658165737-15a047b7a921?w=500'],
    imagenPrincipal: 0,
    precioRegular: 79.99,
    precioOferta: 69.99,
    porcentajeDescuento: 13,
    stock: 89,
    alertaStockMinimo: 15,
    permitirBackorder: false,
    estado: 'publicado',
    tieneVariantes: false,
    variantes: [],
    requiereEnvio: true,
    peso: 0.15,
    tarifaEnvio: 'fija',
    urlSlug: 'auriculares-deportivos-bluetooth',
    vistas: 1567,
    ventas: 178,
    addToCart: 245,
    tasaConversion: 72.7,
    revenueGenerado: 12458.22,
    productosRelacionados: ['44', '46'],
    fechaCreacion: '2024-01-22',
    fechaActualizacion: '2024-12-02',
  },
  {
    id: '46',
    nombre: 'Brazalete Porta Móvil Running',
    descripcionCorta: 'Brazalete ajustable para smartphone',
    descripcionLarga: 'Brazalete deportivo con pantalla táctil transparente. Compatible con smartphones hasta 6.5 pulgadas.',
    categoria: 'Accesorios',
    subcategoria: 'Tecnología',
    tags: ['brazalete', 'móvil', 'running'],
    sku: 'TEC-BRA-046',
    imagenes: ['https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=500'],
    imagenPrincipal: 0,
    precioRegular: 14.99,
    stock: 167,
    alertaStockMinimo: 25,
    permitirBackorder: true,
    estado: 'publicado',
    tieneVariantes: false,
    variantes: [],
    requiereEnvio: true,
    peso: 0.1,
    tarifaEnvio: 'fija',
    urlSlug: 'brazalete-porta-movil-running',
    vistas: 890,
    ventas: 189,
    addToCart: 234,
    tasaConversion: 80.8,
    revenueGenerado: 2832.11,
    productosRelacionados: ['45', '24'],
    fechaCreacion: '2024-02-08',
    fechaActualizacion: '2024-12-01',
  },
  {
    id: '47',
    nombre: 'Riñonera Running Impermeable',
    descripcionCorta: 'Riñonera con bolsillos expandibles',
    descripcionLarga: 'Riñonera ultra ligera e impermeable con múltiples compartimentos. Perfecta para guardar llaves, móvil y geles.',
    categoria: 'Accesorios',
    subcategoria: 'Bolsas',
    tags: ['riñonera', 'running', 'impermeable'],
    sku: 'ACC-RIÑ-047',
    imagenes: ['https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?w=500'],
    imagenPrincipal: 0,
    precioRegular: 19.99,
    stock: 145,
    alertaStockMinimo: 20,
    permitirBackorder: false,
    estado: 'publicado',
    tieneVariantes: false,
    variantes: [],
    requiereEnvio: true,
    peso: 0.1,
    tarifaEnvio: 'fija',
    urlSlug: 'rinonera-running-impermeable',
    vistas: 678,
    ventas: 134,
    addToCart: 178,
    tasaConversion: 75.3,
    revenueGenerado: 2678.66,
    productosRelacionados: ['24', '46'],
    fechaCreacion: '2024-02-18',
    fechaActualizacion: '2024-11-30',
  },
  {
    id: '48',
    nombre: 'Cronómetro Digital Profesional',
    descripcionCorta: 'Cronómetro con 100 memorias y cuenta regresiva',
    descripcionLarga: 'Cronómetro profesional con pantalla LCD grande, memoria de 100 tiempos y función de cuenta regresiva.',
    categoria: 'Accesorios',
    subcategoria: 'Tecnología',
    tags: ['cronómetro', 'digital', 'profesional'],
    sku: 'TEC-CRO-048',
    imagenes: ['https://images.unsplash.com/photo-1495364037436-fed1ba81ad3e?w=500'],
    imagenPrincipal: 0,
    precioRegular: 29.99,
    stock: 67,
    alertaStockMinimo: 12,
    permitirBackorder: true,
    estado: 'borrador',
    tieneVariantes: false,
    variantes: [],
    requiereEnvio: true,
    peso: 0.15,
    tarifaEnvio: 'fija',
    urlSlug: 'cronometro-digital-profesional',
    vistas: 234,
    ventas: 23,
    addToCart: 45,
    tasaConversion: 51.1,
    revenueGenerado: 689.77,
    productosRelacionados: ['44', '36'],
    fechaCreacion: '2024-03-12',
    fechaActualizacion: '2024-11-25',
  },
  {
    id: '49',
    nombre: 'Pulsera Actividad Fitness',
    descripcionCorta: 'Pulsera inteligente con monitor de sueño',
    descripcionLarga: 'Pulsera de actividad con monitor de pasos, calorías, sueño y notificaciones. Batería de 10 días.',
    categoria: 'Accesorios',
    subcategoria: 'Tecnología',
    tags: ['pulsera', 'actividad', 'fitness'],
    sku: 'TEC-PUL-049',
    imagenes: ['https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=500'],
    imagenPrincipal: 0,
    precioRegular: 49.99,
    stock: 1,
    alertaStockMinimo: 10,
    permitirBackorder: true,
    estado: 'publicado',
    tieneVariantes: true,
    variantes: [
      { id: 'v62', color: 'Negro', sku: 'TEC-PUL-049-NEG', stock: 1 },
      { id: 'v63', color: 'Rosa', sku: 'TEC-PUL-049-ROS', stock: 0 },
    ],
    requiereEnvio: true,
    peso: 0.1,
    tarifaEnvio: 'fija',
    urlSlug: 'pulsera-actividad-fitness',
    vistas: 1234,
    ventas: 156,
    addToCart: 198,
    tasaConversion: 78.8,
    revenueGenerado: 7798.44,
    productosRelacionados: ['44', '45'],
    fechaCreacion: '2024-01-28',
    fechaActualizacion: '2024-12-04',
  },
  {
    id: '50',
    nombre: 'Báscula Bioimpedancia Inteligente',
    descripcionCorta: 'Báscula digital con análisis corporal completo',
    descripcionLarga: 'Báscula inteligente que mide peso, grasa corporal, masa muscular, IMC y más. Conecta con app móvil.',
    categoria: 'Accesorios',
    subcategoria: 'Tecnología',
    tags: ['báscula', 'bioimpedancia', 'smart'],
    sku: 'TEC-BAS-050',
    imagenes: ['https://images.unsplash.com/photo-1576797409014-e4184d45c61c?w=500'],
    imagenPrincipal: 0,
    precioRegular: 69.99,
    precioOferta: 59.99,
    porcentajeDescuento: 14,
    stock: 78,
    alertaStockMinimo: 12,
    permitirBackorder: false,
    estado: 'publicado',
    tieneVariantes: false,
    variantes: [],
    requiereEnvio: true,
    peso: 2.0,
    dimensiones: { largo: 30, ancho: 30, alto: 3 },
    tarifaEnvio: 'calculada',
    urlSlug: 'bascula-bioimpedancia-inteligente',
    vistas: 1890,
    ventas: 112,
    addToCart: 167,
    tasaConversion: 67.1,
    revenueGenerado: 6718.88,
    productosRelacionados: ['44', '49'],
    fechaCreacion: '2024-02-05',
    fechaActualizacion: '2024-12-03',
  },
];

// Función para simular API - devuelve datos mockeados
export const getProductos = async (): Promise<Producto[]> => {
  // Simular delay de red
  await new Promise(resolve => setTimeout(resolve, 500));
  return PRODUCTOS_MOCK;
};

export const getProductoById = async (id: string): Promise<Producto | undefined> => {
  await new Promise(resolve => setTimeout(resolve, 300));
  return PRODUCTOS_MOCK.find(p => p.id === id);
};

export const createProducto = async (producto: Omit<Producto, 'id'>): Promise<Producto> => {
  await new Promise(resolve => setTimeout(resolve, 500));
  const nuevoProducto: Producto = {
    ...producto,
    id: `PROD-${Date.now()}`,
    fechaCreacion: new Date().toISOString().split('T')[0],
    fechaActualizacion: new Date().toISOString().split('T')[0],
  };
  PRODUCTOS_MOCK.push(nuevoProducto);
  return nuevoProducto;
};

export const updateProducto = async (id: string, producto: Partial<Producto>): Promise<Producto | undefined> => {
  await new Promise(resolve => setTimeout(resolve, 500));
  const index = PRODUCTOS_MOCK.findIndex(p => p.id === id);
  if (index !== -1) {
    PRODUCTOS_MOCK[index] = {
      ...PRODUCTOS_MOCK[index],
      ...producto,
      fechaActualizacion: new Date().toISOString().split('T')[0],
    };
    return PRODUCTOS_MOCK[index];
  }
  return undefined;
};

export const deleteProducto = async (id: string): Promise<boolean> => {
  await new Promise(resolve => setTimeout(resolve, 500));
  const index = PRODUCTOS_MOCK.findIndex(p => p.id === id);
  if (index !== -1) {
    PRODUCTOS_MOCK.splice(index, 1);
    return true;
  }
  return false;
};

// Estadísticas del catálogo
export const getEstadisticasCatalogo = () => {
  const totalProductos = PRODUCTOS_MOCK.length;
  const productosPublicados = PRODUCTOS_MOCK.filter(p => p.estado === 'publicado').length;
  const productosAgotados = PRODUCTOS_MOCK.filter(p => p.estado === 'agotado').length;
  const productosStockBajo = PRODUCTOS_MOCK.filter(p => p.stock > 0 && p.stock <= p.alertaStockMinimo).length;

  const valorTotalInventario = PRODUCTOS_MOCK.reduce((total, p) => {
    const precio = p.precioOferta || p.precioRegular;
    return total + (precio * p.stock);
  }, 0);

  return {
    totalProductos,
    productosPublicados,
    productosAgotados,
    productosStockBajo,
    valorTotalInventario,
  };
};
