export interface Campaign {
  id: string;
  name: string;
  objective: string;
  startDate: string;
  endDate: string;
  status: 'planificada' | 'activa' | 'finalizada' | 'pausada';
  budget: number;
  cost: number;
  leadsGenerated: number;
  customersConverted: number;
  roi: number; // Return on Investment
  audienceSegmentation: string;
  template: string;
}

export type EstadoCampana = 'Activa' | 'Programada' | 'Completada' | 'Pausada';
export type CanalCampana = 'email' | 'redes' | 'SMS' | 'web' | 'mixto' | 'instagram' | 'facebook' | 'tiktok' | 'youtube' | 'linkedin' | 'twitter' | 'whatsapp' | 'telegram';

export interface Campana {
  id: string;
  nombre: string;
  descripcion: string;
  estado: EstadoCampana;
  canal: CanalCampana;
  fechaInicio: string;
  fechaFin: string;
  presupuesto: number;
  presupuestoUtilizado: number;
  objetivo: string;
  audienciaObjetivo: string;
  impresiones: number;
  clicks: number;
  conversiones: number;
  ctr: number; // Click Through Rate
  cpc: number; // Cost Per Click
  cpa: number; // Cost Per Acquisition
  roi: number; // Return on Investment
  imagen?: string;
}

export interface EventoCalendario {
  id: string;
  fecha: string;
  campanas: Campana[];
}

export const MOCK_CAMPANAS: Campana[] = [
  {
    id: '1',
    nombre: 'Black Friday 2025',
    descripcion: 'Campaña principal para Black Friday con descuentos especiales',
    estado: 'Activa',
    canal: 'mixto',
    fechaInicio: '2025-11-20',
    fechaFin: '2025-11-30',
    presupuesto: 50000,
    presupuestoUtilizado: 32000,
    objetivo: 'Incrementar ventas 150%',
    audienciaObjetivo: 'Clientes frecuentes y nuevos usuarios',
    impresiones: 850000,
    clicks: 42500,
    conversiones: 3825,
    ctr: 5.0,
    cpc: 0.75,
    cpa: 8.37,
    roi: 285,
    imagen: '🛍️'
  },
  {
    id: '2',
    nombre: 'Lanzamiento Producto X',
    descripcion: 'Presentación del nuevo producto revolucionario',
    estado: 'Activa',
    canal: 'redes',
    fechaInicio: '2025-10-01',
    fechaFin: '2025-10-31',
    presupuesto: 35000,
    presupuestoUtilizado: 28000,
    objetivo: 'Awareness y primeras ventas',
    audienciaObjetivo: 'Early adopters tech-savvy',
    impresiones: 620000,
    clicks: 31000,
    conversiones: 2170,
    ctr: 5.0,
    cpc: 0.90,
    cpa: 12.90,
    roi: 198,
    imagen: '🚀'
  },
  {
    id: '3',
    nombre: 'Email Newsletter Octubre',
    descripcion: 'Newsletter mensual con contenido exclusivo',
    estado: 'Completada',
    canal: 'email',
    fechaInicio: '2025-10-05',
    fechaFin: '2025-10-10',
    presupuesto: 5000,
    presupuestoUtilizado: 4800,
    objetivo: 'Engagement y retención',
    audienciaObjetivo: 'Suscriptores activos',
    impresiones: 45000,
    clicks: 6750,
    conversiones: 540,
    ctr: 15.0,
    cpc: 0.71,
    cpa: 8.89,
    roi: 165,
    imagen: '📧'
  },
  {
    id: '4',
    nombre: 'Cyber Monday Flash Sale',
    descripcion: 'Ventas flash exclusivas para Cyber Monday',
    estado: 'Programada',
    canal: 'web',
    fechaInicio: '2025-12-01',
    fechaFin: '2025-12-02',
    presupuesto: 25000,
    presupuestoUtilizado: 0,
    objetivo: 'Maximizar conversiones en 24h',
    audienciaObjetivo: 'Compradores online activos',
    impresiones: 0,
    clicks: 0,
    conversiones: 0,
    ctr: 0,
    cpc: 0,
    cpa: 0,
    roi: 0,
    imagen: '⚡'
  },
  {
    id: '5',
    nombre: 'Campaña SMS Verano',
    descripcion: 'Promociones de verano vía SMS',
    estado: 'Completada',
    canal: 'SMS',
    fechaInicio: '2025-07-01',
    fechaFin: '2025-07-31',
    presupuesto: 8000,
    presupuestoUtilizado: 7500,
    objetivo: 'Ventas rápidas',
    audienciaObjetivo: 'Base de clientes móvil',
    impresiones: 35000,
    clicks: 10500,
    conversiones: 1400,
    ctr: 30.0,
    cpc: 0.71,
    cpa: 5.36,
    roi: 220,
    imagen: '📱'
  },
  {
    id: '6',
    nombre: 'Navidad 2025 - Preventa',
    descripcion: 'Campaña de preventa navideña con descuentos early bird',
    estado: 'Programada',
    canal: 'mixto',
    fechaInicio: '2025-11-01',
    fechaFin: '2025-12-24',
    presupuesto: 75000,
    presupuestoUtilizado: 0,
    objetivo: 'Máximas ventas del año',
    audienciaObjetivo: 'Todos los segmentos',
    impresiones: 0,
    clicks: 0,
    conversiones: 0,
    ctr: 0,
    cpc: 0,
    cpa: 0,
    roi: 0,
    imagen: '🎄'
  },
  {
    id: '7',
    nombre: 'Reactivación Clientes Inactivos',
    descripcion: 'Campaña para recuperar clientes que no compran hace 6 meses',
    estado: 'Activa',
    canal: 'email',
    fechaInicio: '2025-09-15',
    fechaFin: '2025-10-15',
    presupuesto: 12000,
    presupuestoUtilizado: 9600,
    objetivo: 'Recuperar 15% de inactivos',
    audienciaObjetivo: 'Clientes inactivos 6+ meses',
    impresiones: 28000,
    clicks: 4200,
    conversiones: 560,
    ctr: 15.0,
    cpc: 2.29,
    cpa: 17.14,
    roi: 145,
    imagen: '🔄'
  },
  {
    id: '8',
    nombre: 'Instagram Influencers Septiembre',
    descripcion: 'Colaboración con micro-influencers en Instagram',
    estado: 'Completada',
    canal: 'redes',
    fechaInicio: '2025-09-01',
    fechaFin: '2025-09-30',
    presupuesto: 20000,
    presupuestoUtilizado: 19500,
    objetivo: 'Brand awareness y engagement',
    audienciaObjetivo: 'Millennials y Gen Z',
    impresiones: 450000,
    clicks: 22500,
    conversiones: 1575,
    ctr: 5.0,
    cpc: 0.87,
    cpa: 12.38,
    roi: 175,
    imagen: '📸'
  },
  {
    id: '9',
    nombre: 'Webinar Educativo - SEO Avanzado',
    descripcion: 'Webinar gratuito sobre estrategias SEO',
    estado: 'Completada',
    canal: 'web',
    fechaInicio: '2025-08-15',
    fechaFin: '2025-08-15',
    presupuesto: 3000,
    presupuestoUtilizado: 2800,
    objetivo: 'Lead generation',
    audienciaObjetivo: 'Marketers y empresarios',
    impresiones: 15000,
    clicks: 2250,
    conversiones: 450,
    ctr: 15.0,
    cpc: 1.24,
    cpa: 6.22,
    roi: 320,
    imagen: '🎓'
  },
  {
    id: '10',
    nombre: 'Facebook Ads - Otoño',
    descripcion: 'Campaña publicitaria en Facebook para temporada otoño',
    estado: 'Pausada',
    canal: 'redes',
    fechaInicio: '2025-09-20',
    fechaFin: '2025-10-20',
    presupuesto: 15000,
    presupuestoUtilizado: 8500,
    objetivo: 'Conversiones directas',
    audienciaObjetivo: 'Lookalike audiences',
    impresiones: 280000,
    clicks: 11200,
    conversiones: 672,
    ctr: 4.0,
    cpc: 0.76,
    cpa: 12.65,
    roi: 155,
    imagen: '🍂'
  },
  {
    id: '11',
    nombre: 'TikTok Challenge Viral',
    descripcion: 'Challenge viral con hashtag branded',
    estado: 'Activa',
    canal: 'redes',
    fechaInicio: '2025-10-10',
    fechaFin: '2025-10-24',
    presupuesto: 18000,
    presupuestoUtilizado: 12000,
    objetivo: 'Viralidad y UGC',
    audienciaObjetivo: 'Gen Z 16-24 años',
    impresiones: 1200000,
    clicks: 60000,
    conversiones: 4200,
    ctr: 5.0,
    cpc: 0.20,
    cpa: 2.86,
    roi: 380,
    imagen: '🎵'
  },
  {
    id: '12',
    nombre: 'Google Ads - Keywords Premium',
    descripcion: 'Campaña SEM con keywords de alto valor',
    estado: 'Activa',
    canal: 'web',
    fechaInicio: '2025-10-01',
    fechaFin: '2025-12-31',
    presupuesto: 45000,
    presupuestoUtilizado: 15000,
    objetivo: 'ROI máximo',
    audienciaObjetivo: 'Intent alto de compra',
    impresiones: 180000,
    clicks: 9000,
    conversiones: 1350,
    ctr: 5.0,
    cpc: 1.67,
    cpa: 11.11,
    roi: 210,
    imagen: '🔍'
  },
  {
    id: '13',
    nombre: 'Programa Referidos',
    descripcion: 'Incentivos para clientes que refieren amigos',
    estado: 'Activa',
    canal: 'email',
    fechaInicio: '2025-09-01',
    fechaFin: '2025-12-31',
    presupuesto: 10000,
    presupuestoUtilizado: 3500,
    objetivo: 'Crecimiento orgánico',
    audienciaObjetivo: 'Clientes satisfechos',
    impresiones: 25000,
    clicks: 5000,
    conversiones: 750,
    ctr: 20.0,
    cpc: 0.70,
    cpa: 4.67,
    roi: 425,
    imagen: '🤝'
  },
  {
    id: '14',
    nombre: 'Retargeting Carrito Abandonado',
    descripcion: 'Recuperación de carritos abandonados',
    estado: 'Activa',
    canal: 'mixto',
    fechaInicio: '2025-01-01',
    fechaFin: '2025-12-31',
    presupuesto: 30000,
    presupuestoUtilizado: 25000,
    objetivo: 'Recuperar ventas perdidas',
    audienciaObjetivo: 'Usuarios con carrito abandonado',
    impresiones: 95000,
    clicks: 14250,
    conversiones: 2138,
    ctr: 15.0,
    cpc: 1.75,
    cpa: 11.69,
    roi: 245,
    imagen: '🛒'
  },
  {
    id: '15',
    nombre: 'LinkedIn B2B Outreach',
    descripcion: 'Campaña B2B en LinkedIn para corporativos',
    estado: 'Completada',
    canal: 'redes',
    fechaInicio: '2025-07-01',
    fechaFin: '2025-08-31',
    presupuesto: 22000,
    presupuestoUtilizado: 21000,
    objetivo: 'Leads calificados B2B',
    audienciaObjetivo: 'Decision makers empresas',
    impresiones: 85000,
    clicks: 3400,
    conversiones: 170,
    ctr: 4.0,
    cpc: 6.18,
    cpa: 123.53,
    roi: 180,
    imagen: '💼'
  },
  {
    id: '16',
    nombre: 'YouTube Pre-Roll Ads',
    descripcion: 'Anuncios en videos de YouTube',
    estado: 'Programada',
    canal: 'web',
    fechaInicio: '2025-11-15',
    fechaFin: '2025-12-15',
    presupuesto: 28000,
    presupuestoUtilizado: 0,
    objetivo: 'Awareness masivo',
    audienciaObjetivo: 'Audiencia amplia 18-45',
    impresiones: 0,
    clicks: 0,
    conversiones: 0,
    ctr: 0,
    cpc: 0,
    cpa: 0,
    roi: 0,
    imagen: '🎬'
  },
  {
    id: '17',
    nombre: 'Podcast Sponsorship',
    descripcion: 'Patrocinio de podcasts populares del nicho',
    estado: 'Activa',
    canal: 'mixto',
    fechaInicio: '2025-10-01',
    fechaFin: '2025-12-31',
    presupuesto: 16000,
    presupuestoUtilizado: 5500,
    objetivo: 'Brand awareness nicho',
    audienciaObjetivo: 'Oyentes podcasts tech',
    impresiones: 120000,
    clicks: 3600,
    conversiones: 360,
    ctr: 3.0,
    cpc: 1.53,
    cpa: 15.28,
    roi: 195,
    imagen: '🎙️'
  },
  {
    id: '18',
    nombre: 'Encuesta de Satisfacción',
    descripcion: 'Campaña para recopilar feedback de clientes',
    estado: 'Completada',
    canal: 'email',
    fechaInicio: '2025-09-01',
    fechaFin: '2025-09-15',
    presupuesto: 2000,
    presupuestoUtilizado: 1800,
    objetivo: 'Insights y mejora continua',
    audienciaObjetivo: 'Clientes recientes',
    impresiones: 18000,
    clicks: 5400,
    conversiones: 1080,
    ctr: 30.0,
    cpc: 0.33,
    cpa: 1.67,
    roi: 850,
    imagen: '📊'
  },
  {
    id: '19',
    nombre: 'Campaña Responsabilidad Social',
    descripcion: 'Iniciativa de impacto social y ambiental',
    estado: 'Activa',
    canal: 'mixto',
    fechaInicio: '2025-10-01',
    fechaFin: '2025-10-31',
    presupuesto: 12000,
    presupuestoUtilizado: 8000,
    objetivo: 'Brand reputation',
    audienciaObjetivo: 'Consumidores conscientes',
    impresiones: 380000,
    clicks: 11400,
    conversiones: 570,
    ctr: 3.0,
    cpc: 0.70,
    cpa: 14.04,
    roi: 125,
    imagen: '🌱'
  },
  {
    id: '20',
    nombre: 'App Download Campaign',
    descripcion: 'Campaña para incrementar descargas de app móvil',
    estado: 'Activa',
    canal: 'redes',
    fechaInicio: '2025-09-15',
    fechaFin: '2025-11-15',
    presupuesto: 32000,
    presupuestoUtilizado: 20000,
    objetivo: '50k nuevas descargas',
    audienciaObjetivo: 'Mobile-first users',
    impresiones: 720000,
    clicks: 36000,
    conversiones: 2520,
    ctr: 5.0,
    cpc: 0.56,
    cpa: 7.94,
    roi: 265,
    imagen: '📲'
  }
];
