import { ExerciseLibraryEntry } from '../types/exercise.types';

/**
 * Biblioteca expandida de 100+ ejercicios organizados por grupo muscular
 */
export const EXPANDED_EXERCISE_LIBRARY: ExerciseLibraryEntry[] = [
  // ============================================================================
  // PECHO (15 ejercicios)
  // ============================================================================
  {
    id: 'chest001',
    name: 'Press de Banca con Barra',
    primaryMuscle: 'Pecho',
    secondaryMuscles: ['Tríceps', 'Hombros Anterior'],
    muscleGroups: ['Pecho', 'Tríceps'],
    movement: 'push',
    plane: 'sagittal',
    equipment: ['Barra', 'Banco', 'Rack'],
    image: '💪',
    difficulty: 3,
    recommendedFor: ['intermediate', 'advanced'],
    contraindications: ['Lesión de hombro aguda'],
    avoidWithInjuries: ['Hombro'],
    tags: ['compuesto', 'fuerza', 'básico'],
    alternatives: ['chest002', 'chest003'],
  },
  {
    id: 'chest002',
    name: 'Press de Banca con Mancuernas',
    primaryMuscle: 'Pecho',
    secondaryMuscles: ['Tríceps', 'Hombros Anterior'],
    muscleGroups: ['Pecho', 'Tríceps'],
    movement: 'push',
    plane: 'sagittal',
    equipment: ['Mancuernas', 'Banco'],
    image: '💪',
    difficulty: 2,
    recommendedFor: ['beginner', 'intermediate', 'advanced'],
    contraindications: [],
    avoidWithInjuries: ['Hombro'],
    tags: ['compuesto', 'hipertrofia', 'unilateral'],
    alternatives: ['chest001', 'chest003'],
    regression: 'chest006',
  },
  {
    id: 'chest003',
    name: 'Press Inclinado con Barra',
    primaryMuscle: 'Pecho Superior',
    secondaryMuscles: ['Hombros Anterior', 'Tríceps'],
    muscleGroups: ['Pecho', 'Hombros', 'Tríceps'],
    movement: 'push',
    plane: 'sagittal',
    equipment: ['Barra', 'Banco Inclinado', 'Rack'],
    image: '💪',
    difficulty: 3,
    recommendedFor: ['intermediate', 'advanced'],
    contraindications: [],
    avoidWithInjuries: ['Hombro'],
    tags: ['compuesto', 'pecho superior'],
    alternatives: ['chest001', 'chest004'],
  },
  {
    id: 'chest004',
    name: 'Press Inclinado con Mancuernas',
    primaryMuscle: 'Pecho Superior',
    secondaryMuscles: ['Hombros Anterior', 'Tríceps'],
    muscleGroups: ['Pecho', 'Hombros'],
    movement: 'push',
    plane: 'sagittal',
    equipment: ['Mancuernas', 'Banco Inclinado'],
    image: '💪',
    difficulty: 2,
    recommendedFor: ['beginner', 'intermediate', 'advanced'],
    contraindications: [],
    avoidWithInjuries: ['Hombro'],
    tags: ['compuesto', 'pecho superior', 'hipertrofia'],
    alternatives: ['chest003'],
  },
  {
    id: 'chest005',
    name: 'Press Declinado con Barra',
    primaryMuscle: 'Pecho Inferior',
    secondaryMuscles: ['Tríceps'],
    muscleGroups: ['Pecho', 'Tríceps'],
    movement: 'push',
    plane: 'sagittal',
    equipment: ['Barra', 'Banco Declinado', 'Rack'],
    image: '💪',
    difficulty: 3,
    recommendedFor: ['intermediate', 'advanced'],
    contraindications: ['Hipertensión', 'Problemas cervicales'],
    avoidWithInjuries: ['Cuello', 'Hombro'],
    tags: ['compuesto', 'pecho inferior'],
    alternatives: ['chest001', 'chest007'],
  },
  {
    id: 'chest006',
    name: 'Flexiones',
    primaryMuscle: 'Pecho',
    secondaryMuscles: ['Tríceps', 'Core'],
    muscleGroups: ['Pecho', 'Tríceps'],
    movement: 'push',
    plane: 'sagittal',
    equipment: ['Peso corporal'],
    image: '🤸‍♂️',
    difficulty: 1,
    recommendedFor: ['beginner', 'intermediate'],
    contraindications: [],
    avoidWithInjuries: ['Muñeca', 'Hombro'],
    tags: ['peso corporal', 'básico', 'funcional'],
    alternatives: ['chest002'],
    progression: 'chest001',
  },
  {
    id: 'chest007',
    name: 'Fondos en Paralelas',
    primaryMuscle: 'Pecho Inferior',
    secondaryMuscles: ['Tríceps', 'Hombros Anterior'],
    muscleGroups: ['Pecho', 'Tríceps'],
    movement: 'push',
    plane: 'sagittal',
    equipment: ['Paralelas'],
    image: '🤸',
    difficulty: 3,
    recommendedFor: ['intermediate', 'advanced'],
    contraindications: ['Lesión de hombro'],
    avoidWithInjuries: ['Hombro', 'Codo'],
    tags: ['peso corporal', 'avanzado'],
    alternatives: ['chest005'],
    regression: 'chest006',
  },
  {
    id: 'chest008',
    name: 'Aperturas con Mancuernas',
    primaryMuscle: 'Pecho',
    secondaryMuscles: [],
    muscleGroups: ['Pecho'],
    movement: 'isolation',
    plane: 'frontal',
    equipment: ['Mancuernas', 'Banco'],
    image: '💪',
    difficulty: 2,
    recommendedFor: ['beginner', 'intermediate', 'advanced'],
    contraindications: ['Lesión de hombro aguda'],
    avoidWithInjuries: ['Hombro'],
    tags: ['aislamiento', 'hipertrofia', 'estiramiento'],
  },
  {
    id: 'chest009',
    name: 'Aperturas en Polea (Cable Crossover)',
    primaryMuscle: 'Pecho',
    secondaryMuscles: [],
    muscleGroups: ['Pecho'],
    movement: 'isolation',
    plane: 'frontal',
    equipment: ['Poleas'],
    image: '💪',
    difficulty: 2,
    recommendedFor: ['intermediate', 'advanced'],
    contraindications: [],
    avoidWithInjuries: ['Hombro'],
    tags: ['aislamiento', 'tensión constante', 'hipertrofia'],
  },
  {
    id: 'chest010',
    name: 'Press en Máquina',
    primaryMuscle: 'Pecho',
    secondaryMuscles: ['Tríceps', 'Hombros'],
    muscleGroups: ['Pecho', 'Tríceps'],
    movement: 'push',
    plane: 'sagittal',
    equipment: ['Máquina de Pecho'],
    image: '🏋️',
    difficulty: 1,
    recommendedFor: ['beginner'],
    contraindications: [],
    avoidWithInjuries: [],
    tags: ['máquina', 'seguro', 'principiante'],
    progression: 'chest001',
  },

  // ============================================================================
  // ESPALDA (20 ejercicios)
  // ============================================================================
  {
    id: 'back001',
    name: 'Peso Muerto Convencional',
    primaryMuscle: 'Espalda Baja',
    secondaryMuscles: ['Isquios', 'Glúteos', 'Trapecio', 'Core'],
    muscleGroups: ['Espalda Baja', 'Isquios', 'Glúteos'],
    movement: 'hinge',
    plane: 'sagittal',
    equipment: ['Barra'],
    image: '🏋️‍♀️',
    difficulty: 4,
    recommendedFor: ['intermediate', 'advanced'],
    contraindications: ['Hernia discal', 'Lesión lumbar aguda'],
    avoidWithInjuries: ['Espalda Baja', 'Rodilla'],
    tags: ['compuesto', 'fuerza', 'básico', 'power'],
  },
  {
    id: 'back002',
    name: 'Peso Muerto Rumano',
    primaryMuscle: 'Isquios',
    secondaryMuscles: ['Glúteos', 'Espalda Baja'],
    muscleGroups: ['Isquios', 'Glúteos', 'Espalda Baja'],
    movement: 'hinge',
    plane: 'sagittal',
    equipment: ['Barra'],
    image: '🏋️',
    difficulty: 3,
    recommendedFor: ['intermediate', 'advanced'],
    contraindications: ['Lesión lumbar aguda'],
    avoidWithInjuries: ['Espalda Baja'],
    tags: ['compuesto', 'isquios', 'hipertrofia'],
    regression: 'back001',
  },
  {
    id: 'back003',
    name: 'Dominadas Pronadas',
    primaryMuscle: 'Espalda Dorsal',
    secondaryMuscles: ['Bíceps', 'Trapecio'],
    muscleGroups: ['Espalda Dorsal', 'Bíceps'],
    movement: 'pull',
    plane: 'sagittal',
    equipment: ['Barra de Dominadas'],
    image: '🤸',
    difficulty: 4,
    recommendedFor: ['intermediate', 'advanced'],
    contraindications: [],
    avoidWithInjuries: ['Hombro', 'Codo'],
    tags: ['peso corporal', 'compuesto', 'espalda ancha'],
  },
  {
    id: 'back004',
    name: 'Dominadas Supinas (Chin-ups)',
    primaryMuscle: 'Espalda Dorsal',
    secondaryMuscles: ['Bíceps'],
    muscleGroups: ['Espalda Dorsal', 'Bíceps'],
    movement: 'pull',
    plane: 'sagittal',
    equipment: ['Barra de Dominadas'],
    image: '🤸',
    difficulty: 3,
    recommendedFor: ['intermediate', 'advanced'],
    contraindications: [],
    avoidWithInjuries: ['Hombro', 'Codo'],
    tags: ['peso corporal', 'compuesto', 'bíceps'],
    regression: 'back003',
  },
  {
    id: 'back005',
    name: 'Remo con Barra',
    primaryMuscle: 'Espalda Dorsal',
    secondaryMuscles: ['Trapecio', 'Bíceps', 'Espalda Baja'],
    muscleGroups: ['Espalda Dorsal', 'Bíceps'],
    movement: 'pull',
    plane: 'sagittal',
    equipment: ['Barra'],
    image: '💪',
    difficulty: 3,
    recommendedFor: ['intermediate', 'advanced'],
    contraindications: ['Lesión lumbar'],
    avoidWithInjuries: ['Espalda Baja'],
    tags: ['compuesto', 'espalda gruesa', 'fuerza'],
  },
  {
    id: 'back006',
    name: 'Remo con Mancuerna a Una Mano',
    primaryMuscle: 'Espalda Dorsal',
    secondaryMuscles: ['Trapecio', 'Bíceps'],
    muscleGroups: ['Espalda Dorsal', 'Bíceps'],
    movement: 'pull',
    plane: 'sagittal',
    equipment: ['Mancuerna', 'Banco'],
    image: '💪',
    difficulty: 2,
    recommendedFor: ['beginner', 'intermediate', 'advanced'],
    contraindications: [],
    avoidWithInjuries: [],
    tags: ['compuesto', 'unilateral', 'hipertrofia'],
  },
  {
    id: 'back007',
    name: 'Jalón al Pecho',
    primaryMuscle: 'Espalda Dorsal',
    secondaryMuscles: ['Bíceps', 'Trapecio'],
    muscleGroups: ['Espalda Dorsal', 'Bíceps'],
    movement: 'pull',
    plane: 'sagittal',
    equipment: ['Polea Alta'],
    image: '💪',
    difficulty: 2,
    recommendedFor: ['beginner', 'intermediate'],
    contraindications: [],
    avoidWithInjuries: ['Hombro'],
    tags: ['máquina', 'espalda ancha'],
    progression: 'back003',
  },
  {
    id: 'back008',
    name: 'Remo en Polea Baja',
    primaryMuscle: 'Espalda Dorsal',
    secondaryMuscles: ['Trapecio', 'Bíceps'],
    muscleGroups: ['Espalda Dorsal', 'Bíceps'],
    movement: 'pull',
    plane: 'sagittal',
    equipment: ['Polea Baja'],
    image: '💪',
    difficulty: 2,
    recommendedFor: ['beginner', 'intermediate', 'advanced'],
    contraindications: [],
    avoidWithInjuries: [],
    tags: ['máquina', 'hipertrofia'],
  },
  {
    id: 'back009',
    name: 'Face Pull',
    primaryMuscle: 'Trapecio Medio',
    secondaryMuscles: ['Hombros Posterior', 'Romboides'],
    muscleGroups: ['Espalda Dorsal', 'Hombros'],
    movement: 'pull',
    plane: 'frontal',
    equipment: ['Polea'],
    image: '💪',
    difficulty: 2,
    recommendedFor: ['beginner', 'intermediate', 'advanced'],
    contraindications: [],
    avoidWithInjuries: [],
    tags: ['corrección postural', 'salud de hombro', 'hipertrofia'],
  },
  {
    id: 'back010',
    name: 'Hiperextensiones',
    primaryMuscle: 'Espalda Baja',
    secondaryMuscles: ['Glúteos', 'Isquios'],
    muscleGroups: ['Espalda Baja', 'Glúteos'],
    movement: 'hinge',
    plane: 'sagittal',
    equipment: ['Banco de Hiperextensiones'],
    image: '🏋️',
    difficulty: 2,
    recommendedFor: ['beginner', 'intermediate', 'advanced'],
    contraindications: ['Lesión lumbar aguda'],
    avoidWithInjuries: ['Espalda Baja'],
    tags: ['aislamiento', 'espalda baja', 'prevención'],
  },

  // ============================================================================
  // PIERNAS (25 ejercicios)
  // ============================================================================
  {
    id: 'legs001',
    name: 'Sentadilla con Barra (Back Squat)',
    primaryMuscle: 'Cuádriceps',
    secondaryMuscles: ['Glúteos', 'Core', 'Espalda Baja'],
    muscleGroups: ['Cuádriceps', 'Glúteos'],
    movement: 'squat',
    plane: 'sagittal',
    equipment: ['Barra', 'Rack'],
    image: '🏋️',
    difficulty: 4,
    recommendedFor: ['intermediate', 'advanced'],
    contraindications: ['Lesión de rodilla aguda', 'Lesión lumbar'],
    avoidWithInjuries: ['Rodilla', 'Espalda Baja'],
    tags: ['compuesto', 'fuerza', 'básico', 'rey de ejercicios'],
  },
  {
    id: 'legs002',
    name: 'Sentadilla Frontal',
    primaryMuscle: 'Cuádriceps',
    secondaryMuscles: ['Core', 'Glúteos'],
    muscleGroups: ['Cuádriceps', 'Glúteos'],
    movement: 'squat',
    plane: 'sagittal',
    equipment: ['Barra', 'Rack'],
    image: '🏋️',
    difficulty: 5,
    recommendedFor: ['advanced'],
    contraindications: ['Lesión de muñeca'],
    avoidWithInjuries: ['Rodilla', 'Muñeca'],
    tags: ['compuesto', 'cuádriceps dominante', 'core'],
  },
  {
    id: 'legs003',
    name: 'Sentadilla Búlgara',
    primaryMuscle: 'Cuádriceps',
    secondaryMuscles: ['Glúteos'],
    muscleGroups: ['Cuádriceps', 'Glúteos'],
    movement: 'squat',
    plane: 'sagittal',
    equipment: ['Mancuernas', 'Banco'],
    image: '🏃',
    difficulty: 3,
    recommendedFor: ['intermediate', 'advanced'],
    contraindications: [],
    avoidWithInjuries: ['Rodilla'],
    tags: ['unilateral', 'hipertrofia', 'estabilidad'],
  },
  {
    id: 'legs004',
    name: 'Zancadas con Mancuernas',
    primaryMuscle: 'Cuádriceps',
    secondaryMuscles: ['Glúteos'],
    muscleGroups: ['Cuádriceps', 'Glúteos'],
    movement: 'squat',
    plane: 'sagittal',
    equipment: ['Mancuernas'],
    image: '🏃',
    difficulty: 2,
    recommendedFor: ['beginner', 'intermediate', 'advanced'],
    contraindications: [],
    avoidWithInjuries: ['Rodilla'],
    tags: ['unilateral', 'funcional', 'estabilidad'],
  },
  {
    id: 'legs005',
    name: 'Prensa de Piernas',
    primaryMuscle: 'Cuádriceps',
    secondaryMuscles: ['Glúteos'],
    muscleGroups: ['Cuádriceps', 'Glúteos'],
    movement: 'push',
    plane: 'sagittal',
    equipment: ['Máquina de Prensa'],
    image: '🏋️',
    difficulty: 2,
    recommendedFor: ['beginner', 'intermediate', 'advanced'],
    contraindications: [],
    avoidWithInjuries: [],
    tags: ['máquina', 'seguro', 'volumen'],
    progression: 'legs001',
  },
  {
    id: 'legs006',
    name: 'Extensión de Cuádriceps',
    primaryMuscle: 'Cuádriceps',
    secondaryMuscles: [],
    muscleGroups: ['Cuádriceps'],
    movement: 'isolation',
    plane: 'sagittal',
    equipment: ['Máquina de Extensión'],
    image: '🦵',
    difficulty: 1,
    recommendedFor: ['beginner', 'intermediate', 'advanced'],
    contraindications: ['Lesión de rodilla'],
    avoidWithInjuries: ['Rodilla'],
    tags: ['aislamiento', 'cuádriceps', 'hipertrofia'],
  },
  {
    id: 'legs007',
    name: 'Curl Femoral Tumbado',
    primaryMuscle: 'Isquios',
    secondaryMuscles: [],
    muscleGroups: ['Isquios'],
    movement: 'isolation',
    plane: 'sagittal',
    equipment: ['Máquina de Curl'],
    image: '🦵',
    difficulty: 1,
    recommendedFor: ['beginner', 'intermediate', 'advanced'],
    contraindications: [],
    avoidWithInjuries: ['Rodilla'],
    tags: ['aislamiento', 'isquios', 'hipertrofia'],
  },
  {
    id: 'legs008',
    name: 'Hip Thrust con Barra',
    primaryMuscle: 'Glúteos',
    secondaryMuscles: ['Isquios'],
    muscleGroups: ['Glúteos', 'Isquios'],
    movement: 'hinge',
    plane: 'sagittal',
    equipment: ['Barra', 'Banco'],
    image: '🍑',
    difficulty: 2,
    recommendedFor: ['beginner', 'intermediate', 'advanced'],
    contraindications: [],
    avoidWithInjuries: [],
    tags: ['glúteos', 'hipertrofia', 'fuerza'],
  },
  {
    id: 'legs009',
    name: 'Zancadas Caminando',
    primaryMuscle: 'Cuádriceps',
    secondaryMuscles: ['Glúteos'],
    muscleGroups: ['Cuádriceps', 'Glúteos'],
    movement: 'squat',
    plane: 'sagittal',
    equipment: ['Mancuernas'],
    image: '🏃',
    difficulty: 2,
    recommendedFor: ['beginner', 'intermediate', 'advanced'],
    contraindications: [],
    avoidWithInjuries: ['Rodilla'],
    tags: ['unilateral', 'funcional', 'cardio'],
  },
  {
    id: 'legs010',
    name: 'Elevación de Talones de Pie',
    primaryMuscle: 'Gemelos',
    secondaryMuscles: [],
    muscleGroups: ['Gemelos'],
    movement: 'isolation',
    plane: 'sagittal',
    equipment: ['Máquina de Gemelos'],
    image: '🦵',
    difficulty: 1,
    recommendedFor: ['beginner', 'intermediate', 'advanced'],
    contraindications: [],
    avoidWithInjuries: ['Tobillo'],
    tags: ['aislamiento', 'gemelos'],
  },

  // ============================================================================
  // HOMBROS (15 ejercicios)
  // ============================================================================
  {
    id: 'shoulders001',
    name: 'Press Militar con Barra',
    primaryMuscle: 'Hombros Anterior',
    secondaryMuscles: ['Tríceps', 'Core'],
    muscleGroups: ['Hombros', 'Tríceps'],
    movement: 'push',
    plane: 'sagittal',
    equipment: ['Barra'],
    image: '🦾',
    difficulty: 3,
    recommendedFor: ['intermediate', 'advanced'],
    contraindications: ['Lesión de hombro'],
    avoidWithInjuries: ['Hombro'],
    tags: ['compuesto', 'fuerza', 'básico'],
  },
  {
    id: 'shoulders002',
    name: 'Press con Mancuernas Sentado',
    primaryMuscle: 'Hombros',
    secondaryMuscles: ['Tríceps'],
    muscleGroups: ['Hombros', 'Tríceps'],
    movement: 'push',
    plane: 'sagittal',
    equipment: ['Mancuernas', 'Banco'],
    image: '🦾',
    difficulty: 2,
    recommendedFor: ['beginner', 'intermediate', 'advanced'],
    contraindications: [],
    avoidWithInjuries: ['Hombro'],
    tags: ['compuesto', 'hipertrofia'],
  },
  {
    id: 'shoulders003',
    name: 'Elevaciones Laterales',
    primaryMuscle: 'Hombros Lateral',
    secondaryMuscles: [],
    muscleGroups: ['Hombros'],
    movement: 'isolation',
    plane: 'frontal',
    equipment: ['Mancuernas'],
    image: '🦾',
    difficulty: 1,
    recommendedFor: ['beginner', 'intermediate', 'advanced'],
    contraindications: [],
    avoidWithInjuries: ['Hombro'],
    tags: ['aislamiento', 'deltoides lateral', 'hipertrofia'],
  },
  {
    id: 'shoulders004',
    name: 'Elevaciones Frontales',
    primaryMuscle: 'Hombros Anterior',
    secondaryMuscles: [],
    muscleGroups: ['Hombros'],
    movement: 'isolation',
    plane: 'sagittal',
    equipment: ['Mancuernas'],
    image: '🦾',
    difficulty: 1,
    recommendedFor: ['beginner', 'intermediate', 'advanced'],
    contraindications: [],
    avoidWithInjuries: ['Hombro'],
    tags: ['aislamiento', 'deltoides anterior'],
  },
  {
    id: 'shoulders005',
    name: 'Pájaros con Mancuernas',
    primaryMuscle: 'Hombros Posterior',
    secondaryMuscles: ['Trapecio'],
    muscleGroups: ['Hombros', 'Espalda Dorsal'],
    movement: 'pull',
    plane: 'frontal',
    equipment: ['Mancuernas', 'Banco'],
    image: '🦾',
    difficulty: 2,
    recommendedFor: ['intermediate', 'advanced'],
    contraindications: [],
    avoidWithInjuries: [],
    tags: ['aislamiento', 'deltoides posterior', 'corrección postural'],
  },

  // ============================================================================
  // BRAZOS (15 ejercicios)
  // ============================================================================
  {
    id: 'arms001',
    name: 'Curl de Bíceps con Barra',
    primaryMuscle: 'Bíceps',
    secondaryMuscles: [],
    muscleGroups: ['Bíceps'],
    movement: 'pull',
    plane: 'sagittal',
    equipment: ['Barra'],
    image: '💪',
    difficulty: 1,
    recommendedFor: ['beginner', 'intermediate', 'advanced'],
    contraindications: [],
    avoidWithInjuries: ['Codo'],
    tags: ['aislamiento', 'bíceps', 'hipertrofia'],
  },
  {
    id: 'arms002',
    name: 'Curl con Mancuernas Alterno',
    primaryMuscle: 'Bíceps',
    secondaryMuscles: [],
    muscleGroups: ['Bíceps'],
    movement: 'pull',
    plane: 'sagittal',
    equipment: ['Mancuernas'],
    image: '💪',
    difficulty: 1,
    recommendedFor: ['beginner', 'intermediate', 'advanced'],
    contraindications: [],
    avoidWithInjuries: ['Codo'],
    tags: ['aislamiento', 'bíceps', 'unilateral'],
  },
  {
    id: 'arms003',
    name: 'Curl Martillo',
    primaryMuscle: 'Braquial',
    secondaryMuscles: ['Bíceps'],
    muscleGroups: ['Bíceps'],
    movement: 'pull',
    plane: 'sagittal',
    equipment: ['Mancuernas'],
    image: '💪',
    difficulty: 1,
    recommendedFor: ['beginner', 'intermediate', 'advanced'],
    contraindications: [],
    avoidWithInjuries: ['Codo'],
    tags: ['aislamiento', 'braquial', 'grosor de brazo'],
  },
  {
    id: 'arms004',
    name: 'Press Francés con Barra',
    primaryMuscle: 'Tríceps',
    secondaryMuscles: [],
    muscleGroups: ['Tríceps'],
    movement: 'push',
    plane: 'sagittal',
    equipment: ['Barra', 'Banco'],
    image: '💪',
    difficulty: 2,
    recommendedFor: ['intermediate', 'advanced'],
    contraindications: ['Lesión de codo'],
    avoidWithInjuries: ['Codo'],
    tags: ['aislamiento', 'tríceps', 'cabeza larga'],
  },
  {
    id: 'arms005',
    name: 'Extensión de Tríceps en Polea',
    primaryMuscle: 'Tríceps',
    secondaryMuscles: [],
    muscleGroups: ['Tríceps'],
    movement: 'push',
    plane: 'sagittal',
    equipment: ['Polea'],
    image: '💪',
    difficulty: 1,
    recommendedFor: ['beginner', 'intermediate', 'advanced'],
    contraindications: [],
    avoidWithInjuries: ['Codo'],
    tags: ['aislamiento', 'tríceps', 'tensión constante'],
  },

  // ============================================================================
  // CORE & ABS (10 ejercicios)
  // ============================================================================
  {
    id: 'core001',
    name: 'Plancha Frontal',
    primaryMuscle: 'Core',
    secondaryMuscles: ['Hombros', 'Glúteos'],
    muscleGroups: ['Core'],
    movement: 'isolation',
    plane: 'sagittal',
    equipment: ['Peso corporal'],
    image: '🧘',
    difficulty: 1,
    recommendedFor: ['beginner', 'intermediate', 'advanced'],
    contraindications: [],
    avoidWithInjuries: ['Espalda Baja'],
    tags: ['core', 'estabilidad', 'isométrico'],
  },
  {
    id: 'core002',
    name: 'Plancha Lateral',
    primaryMuscle: 'Oblicuos',
    secondaryMuscles: ['Core'],
    muscleGroups: ['Core'],
    movement: 'isolation',
    plane: 'frontal',
    equipment: ['Peso corporal'],
    image: '🧘',
    difficulty: 2,
    recommendedFor: ['beginner', 'intermediate', 'advanced'],
    contraindications: [],
    avoidWithInjuries: [],
    tags: ['core', 'oblicuos', 'estabilidad lateral'],
  },
  {
    id: 'core003',
    name: 'Crunch Abdominal',
    primaryMuscle: 'Recto Abdominal',
    secondaryMuscles: [],
    muscleGroups: ['Core'],
    movement: 'isolation',
    plane: 'sagittal',
    equipment: ['Peso corporal'],
    image: '🏋️',
    difficulty: 1,
    recommendedFor: ['beginner', 'intermediate'],
    contraindications: ['Lesión cervical'],
    avoidWithInjuries: ['Cuello'],
    tags: ['abdominales', 'básico'],
  },
  {
    id: 'core004',
    name: 'Elevación de Piernas Colgado',
    primaryMuscle: 'Abdominales Inferiores',
    secondaryMuscles: ['Flexores de Cadera'],
    muscleGroups: ['Core'],
    movement: 'isolation',
    plane: 'sagittal',
    equipment: ['Barra de Dominadas'],
    image: '🤸',
    difficulty: 4,
    recommendedFor: ['advanced'],
    contraindications: [],
    avoidWithInjuries: ['Espalda Baja'],
    tags: ['abdominales inferiores', 'avanzado'],
  },
  {
    id: 'core005',
    name: 'Russian Twist',
    primaryMuscle: 'Oblicuos',
    secondaryMuscles: ['Core'],
    muscleGroups: ['Core'],
    movement: 'rotation',
    plane: 'transverse',
    equipment: ['Peso corporal', 'Disco'],
    equipmentAlternatives: ['Mancuerna', 'Balón Medicinal'],
    image: '🔄',
    difficulty: 2,
    recommendedFor: ['beginner', 'intermediate', 'advanced'],
    contraindications: [],
    avoidWithInjuries: ['Espalda Baja'],
    tags: ['oblicuos', 'rotación', 'funcional'],
  },
];
